/**
 * Expanded Seed Data for Reading Assessments
 * 
 * Contains additional passages, word lists, and comprehension questions
 * to make the assessment more realistic and challenging.
 * 
 * All content is original or public domain.
 * @module reading-assessment-seed-expanded
 */

// ============================================================================
// EXPANDED PASSAGES - 6 per level band (24 total)
// ============================================================================

export const EXPANDED_PASSAGES = [
  // BEGINNER (70-110 words) - 5 more passages
  {
    id: 'passage-b01',
    title: 'The Red Ball',
    levelBand: 'beginner',
    text: 'Sam had a red ball. He liked to play with it in the park. One day, the ball went over the fence. Sam was sad. A kind dog found the ball. The dog brought it back to Sam. Sam was so happy. He gave the dog a pat on the head. They played together all day. Sam and the dog became good friends. Now they play every day in the park.',
    wordCount: 82,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['phonics-focus', 'short-vowels'],
  },
  {
    id: 'passage-b02',
    title: 'My Pet Cat',
    levelBand: 'beginner',
    text: 'I have a pet cat named Spot. She is soft and fluffy. Spot likes to sleep on my bed. She eats fish and milk. In the morning, Spot wakes me up. She rubs her head on my hand. We play with a toy mouse. Spot runs fast and jumps high. At night, she purrs when I pet her. I love my cat very much. She is my best friend.',
    wordCount: 78,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['phonics-focus', 'short-vowels', 'pets'],
  },
  {
    id: 'passage-b03',
    title: 'At the Farm',
    levelBand: 'beginner',
    text: 'We went to a farm today. I saw many animals there. The cows said moo. The pigs were in the mud. The chickens had soft chicks. I fed the goats some hay. A horse let me pet its nose. The farmer showed us a big barn. We picked some red apples from a tree. It was a fun day at the farm. I want to go back soon.',
    wordCount: 76,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['phonics-focus', 'farm', 'animals'],
  },
  {
    id: 'passage-b04',
    title: 'Rain Day',
    levelBand: 'beginner',
    text: 'Today it is raining outside. I can hear the drops on the roof. Drip, drop, drip, drop. I cannot go out to play. So I will stay inside today. I can read a book. I can draw a picture. I can play with my toys. Maybe I will bake with Mom. Rain can be fun too. When it stops, I will jump in the puddles. Splash!',
    wordCount: 71,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['phonics-focus', 'weather'],
  },
  {
    id: 'passage-b05',
    title: 'The Big Tree',
    levelBand: 'beginner',
    text: 'There is a big tree in my garden. It has many green leaves. Birds like to sit in the tree. They sing songs every morning. A squirrel lives in the tree too. It has a nest made of sticks. In summer, the tree gives us shade. In autumn, the leaves turn red and yellow. They fall to the ground. I like to jump in the leaf piles. The tree is my favorite thing in our garden.',
    wordCount: 84,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['phonics-focus', 'nature', 'seasons'],
  },

  // ELEMENTARY (130-200 words) - 5 more passages
  {
    id: 'passage-e01',
    title: 'The School Garden',
    levelBand: 'elementary',
    text: 'Our class started a garden at school this spring. First, we dug up the soil and made it soft and ready for planting. Each student chose a vegetable to grow. I picked tomatoes because they are my favorite. We planted seeds in small holes and covered them with dirt. Every day, we watered our plants and pulled out the weeds that tried to grow nearby. After many weeks, tiny green sprouts pushed through the soil. It was exciting to watch them get bigger each day. By summer, we had tomatoes, carrots, beans, and lettuce growing in our garden. The tomatoes turned from green to red when they were ready to eat. We shared our vegetables with the whole school at a special lunch. Everyone said they tasted better than the ones from the store. Next year, we want to make the garden even bigger.',
    wordCount: 152,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['gardening', 'school', 'science'],
  },
  {
    id: 'passage-e02',
    title: 'Learning to Ride',
    levelBand: 'elementary',
    text: 'Last summer, I learned how to ride a bicycle. At first, I was very scared because I kept falling off. My dad held onto the back of the seat to help me balance. He ran beside me as I pedaled down the street. One day, he let go without telling me. I kept going all by myself! When I looked back and saw him standing far away, I was so surprised that I almost fell. But I stayed on the bike and made it to the end of the street. Now I can ride everywhere. I go to the park, to my friend house, and sometimes to the corner shop with my mom. Riding a bike is one of my favorite things to do. It makes me feel free, like I can go anywhere. My little brother is learning now, and I help him just like Dad helped me.',
    wordCount: 158,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['growing-up', 'family', 'skills'],
  },
  {
    id: 'passage-e03',
    title: 'The Busy Bees',
    levelBand: 'elementary',
    text: 'Honeybees are some of the hardest working creatures in nature. A single hive can have thousands of bees, and each one has an important job to do. The queen bee is the most important because she lays all the eggs. Worker bees are females who do many tasks. Some guard the hive entrance while others build the honeycomb from wax. Forager bees fly out to collect nectar and pollen from flowers. They do a special dance to tell other bees where to find the best flowers. When bees visit flowers, they help spread pollen, which helps new plants grow. This is called pollination, and it is very important for growing our food. Bees make honey by turning nectar into a thick, sweet liquid. They store it in the honeycomb to eat during winter when there are no flowers. Without bees, we would have much less fruit and vegetables to eat.',
    wordCount: 162,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'nature', 'insects'],
  },
  {
    id: 'passage-e04',
    title: 'A Trip to the Aquarium',
    levelBand: 'elementary',
    text: 'Yesterday, my class went on a trip to the city aquarium. We rode a big yellow bus for thirty minutes to get there. When we arrived, a guide met us at the door and took us on a tour. The first tank we saw was full of colorful tropical fish. They had stripes and spots in orange, blue, and yellow. Next, we walked through an underwater tunnel where sharks swam right over our heads! I was a little scared at first, but our guide said the thick glass keeps everyone safe. We also saw playful sea otters floating on their backs and jellyfish that glowed in the dark. My favorite part was the touch tank where we could feel starfish and sea cucumbers. They felt bumpy and squishy. At the gift shop, I bought a small stuffed penguin to remember our trip. I learned so much about ocean animals and cannot wait to go back.',
    wordCount: 168,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['field-trip', 'ocean', 'animals'],
  },
  {
    id: 'passage-e05',
    title: 'The Lost Puppy',
    levelBand: 'elementary',
    text: 'Maya was walking home from school when she heard a small whimper coming from behind a bush. She bent down and found a tiny brown puppy shivering in the cold. The puppy had no collar and looked very hungry. Maya carefully picked up the puppy and wrapped it in her jacket to keep it warm. She carried it all the way home. Her mother helped her give the puppy some water and a little food. They made a cozy bed from old towels. The next day, Maya and her mom made posters with a picture of the puppy. They hung them all around the neighborhood. Two days later, a girl from the next street came to their door. She was crying with happiness because it was her puppy, Biscuit, who had run away during a storm. Maya was sad to say goodbye, but she was glad that Biscuit was going home. The girl promised Maya could visit Biscuit anytime she wanted.',
    wordCount: 175,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['kindness', 'pets', 'community'],
  },

  // INTERMEDIATE (220-320 words) - 5 more passages
  {
    id: 'passage-i01',
    title: 'The Water Cycle',
    levelBand: 'intermediate',
    text: 'The water cycle is one of nature most important processes, continuously moving water around our planet in an endless loop. It begins when the sun heats water in oceans, lakes, and rivers, causing it to evaporate and rise into the atmosphere as invisible water vapor. As this vapor rises higher, it encounters cooler temperatures and condenses into tiny water droplets or ice crystals, forming clouds. When these droplets combine and become too heavy, they fall back to Earth as precipitation, which can take the form of rain, snow, sleet, or hail depending on the temperature. Some of this water flows into streams and rivers, eventually returning to the ocean. Other water soaks into the ground, becoming groundwater that plants can use or that slowly makes its way back to larger bodies of water. Living things also participate in the water cycle. Plants absorb water through their roots and release some back into the air through their leaves in a process called transpiration. Animals drink water and return it to the environment through breathing and other body processes. The water cycle has been operating for billions of years, and the same water molecules that exist today have been recycled countless times. The water you drink today might have once been part of a dinosaur, a cloud over ancient Rome, or a glacier in Antarctica. Understanding the water cycle helps us appreciate how precious and interconnected our water resources truly are.',
    wordCount: 244,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'earth-science', 'water'],
  },
  {
    id: 'passage-i02',
    title: 'The History of Chocolate',
    levelBand: 'intermediate',
    text: 'Chocolate has a rich and fascinating history that spans thousands of years and multiple continents. The story begins with the ancient Mayans and Aztecs of Central America, who cultivated cacao trees and used the beans to make a bitter, spicy drink they considered sacred. The Aztec emperor Montezuma reportedly drank dozens of cups of this frothy beverage each day, believing it gave him energy and wisdom. When Spanish explorers arrived in the Americas in the sixteenth century, they encountered this unusual drink and brought cacao beans back to Europe. The Spanish added sugar to make the drink sweeter and more appealing to European tastes. For nearly a century, Spain kept chocolate a secret from the rest of Europe, but eventually the delicious drink spread to France, Italy, and beyond. Chocolate remained a luxury beverage for wealthy Europeans until the Industrial Revolution, when new machines made it possible to produce chocolate more efficiently and cheaply. In the nineteenth century, inventors discovered how to create solid chocolate bars, and soon after, someone figured out how to add milk to make the creamy milk chocolate we know today. Switzerland and Belgium became famous for their chocolate-making skills. Today, chocolate is enjoyed worldwide in countless forms, from candy bars to hot cocoa, from chocolate chip cookies to elaborate desserts. Yet the basic ingredient remains the same humble cacao bean that ancient peoples first cultivated thousands of years ago in the rainforests of Central America.',
    wordCount: 254,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['history', 'food', 'culture'],
  },
  {
    id: 'passage-i03',
    title: 'Coral Reef Ecosystems',
    levelBand: 'intermediate',
    text: 'Coral reefs are often called the rainforests of the sea because they are home to an astonishing variety of marine life. Although they cover less than one percent of the ocean floor, coral reefs support approximately twenty-five percent of all known marine species. These underwater cities are built by tiny animals called coral polyps, which create hard limestone skeletons around their soft bodies. Over thousands of years, these skeletons accumulate to form the massive reef structures we see today. Coral polyps have a special relationship with tiny algae called zooxanthellae that live inside their tissues. The algae use sunlight to make food through photosynthesis and share this energy with the coral. In return, the coral provides the algae with shelter and nutrients. This partnership gives coral its vibrant colors and is essential for reef survival. Coral reefs provide critical services to both marine life and humans. They serve as nurseries for young fish, protect coastlines from storms and erosion, and provide food and income for millions of people through fishing and tourism. Scientists are also discovering that reef organisms produce chemicals that may help treat diseases like cancer and heart disease. Unfortunately, coral reefs around the world are facing serious threats. Climate change is warming ocean waters, causing coral to expel their algae partners and turn white in a process called bleaching. Pollution, overfishing, and coastal development also damage these fragile ecosystems. Conservation efforts are underway to protect remaining reefs and help damaged ones recover, but these magnificent underwater worlds remain in danger.',
    wordCount: 262,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'ocean', 'environment'],
  },
  {
    id: 'passage-i04',
    title: 'The Art of Origami',
    levelBand: 'intermediate',
    text: 'Origami, the ancient Japanese art of paper folding, transforms a simple flat sheet into intricate three-dimensional sculptures without cutting or gluing. The word origami comes from two Japanese words: oru, meaning to fold, and kami, meaning paper. While paper folding existed in various cultures, Japan developed and refined the art form over many centuries. Traditional origami uses a single square sheet of paper, and the folder creates the design through a precise sequence of folds. The most famous origami model is probably the paper crane, which has deep cultural significance in Japan. According to legend, folding one thousand paper cranes will grant the folder a wish. This tradition became especially meaningful after World War Two, when a young girl named Sadako Sasaki folded cranes while hospitalized, hoping to recover from illness caused by radiation. Her story inspired people worldwide to fold cranes as symbols of peace and hope. Modern origami has evolved far beyond traditional designs. Mathematical origami explores complex geometric principles and has led to practical applications in engineering and space exploration. Scientists have used origami folding patterns to design solar panels that can be compactly stored for rocket launches and then unfold in space. Medical researchers are developing origami-inspired stents and surgical tools. Artistic origami has also reached new heights, with some creators producing incredibly lifelike animals and abstract sculptures. Whether you are a beginner folding a simple boat or an expert creating a detailed dragon, origami offers a meditative, creative experience that requires nothing more than patience, precision, and a piece of paper.',
    wordCount: 267,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['art', 'culture', 'japan'],
  },
  {
    id: 'passage-i05',
    title: 'Migration: Nature Epic Journeys',
    levelBand: 'intermediate',
    text: 'Every year, millions of animals across the globe undertake incredible journeys known as migrations. These remarkable travels are driven by the search for food, better weather, or suitable places to breed and raise young. Some of the most impressive migrations occur in the bird world, where species like the Arctic tern travel nearly from pole to pole each year. This small seabird flies approximately forty-four thousand miles annually, experiencing more daylight than any other creature on Earth. Monarch butterflies perform one of the insect world most amazing migrations. Each autumn, millions of these delicate orange and black butterflies travel up to three thousand miles from Canada and the United States to spend winter in the mountains of central Mexico. Remarkably, the butterflies that make this journey have never made it before because monarchs live only a few months. They navigate using an internal compass and the position of the sun. Marine migrations are equally impressive. Gray whales swim over ten thousand miles round-trip between their feeding grounds in Alaska and their breeding lagoons in Mexico. Salmon are famous for their determination to return to the exact stream where they hatched, swimming hundreds of miles upstream against powerful currents to spawn. Even on land, great migrations occur. On the African savanna, over a million wildebeest and zebras travel in a continuous circuit, following the rains to find fresh grass. These mass movements of animals have shaped ecosystems and cultures throughout human history, and protecting migration routes remains crucial for the survival of many species.',
    wordCount: 265,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'nature', 'animals'],
  },

  // ADVANCED (350-500 words) - 5 more passages
  {
    id: 'passage-a01',
    title: 'The Psychology of Decision Making',
    levelBand: 'advanced',
    text: 'Human decision-making is a remarkably complex cognitive process that psychologists and neuroscientists have studied extensively, revealing fascinating insights into how our minds work and often fail to work rationally. Traditional economic theory assumed humans were rational actors who carefully weighed costs and benefits before making choices. However, decades of research have demonstrated that our decisions are frequently influenced by cognitive biases, emotional states, and mental shortcuts that can lead us astray. One of the most influential discoveries in behavioral psychology is the concept of cognitive biases, systematic patterns of deviation from rational judgment. Confirmation bias, for instance, leads people to seek out and remember information that supports their existing beliefs while ignoring contradictory evidence. The availability heuristic causes us to overestimate the likelihood of events that are easily recalled, which is why many people fear airplane crashes more than car accidents despite the latter being statistically far more dangerous. Another powerful influence on decision-making is loss aversion, the tendency to prefer avoiding losses over acquiring equivalent gains. Research suggests that the psychological pain of losing something is approximately twice as powerful as the pleasure of gaining something of equal value. This asymmetry explains why people often make irrational choices to avoid potential losses, even when taking risks would be mathematically advantageous. Emotional states profoundly affect our choices, often in ways we do not consciously recognize. Studies have shown that hunger, fatigue, and stress can significantly impair decision-making ability, leading to more impulsive choices and reduced self-control. Conversely, positive emotions can sometimes lead to overconfidence and insufficient consideration of risks. The prefrontal cortex, responsible for executive functions like planning and impulse control, can be overwhelmed when we face too many decisions, a phenomenon known as decision fatigue. Understanding these limitations has practical implications for designing better systems and policies. Choice architecture, the practice of structuring decisions to guide people toward beneficial outcomes, has been applied in areas ranging from retirement savings to organ donation. By making positive choices the default option or simplifying complex decisions, we can help people make better choices without restricting their freedom. Recognizing our own cognitive biases and developing strategies to counteract them, such as delaying important decisions, seeking diverse perspectives, and establishing clear criteria before evaluating options, can improve personal decision-making. While we may never achieve perfect rationality, awareness of our mental quirks can help us navigate choices more wisely in an increasingly complex world.',
    wordCount: 387,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['psychology', 'science', 'cognition'],
  },
  {
    id: 'passage-a02',
    title: 'Renewable Energy: Challenges and Progress',
    levelBand: 'advanced',
    text: 'The transition from fossil fuels to renewable energy sources represents one of the most significant technological and economic transformations in human history. As concerns about climate change intensify and the environmental costs of carbon-based energy become increasingly apparent, nations worldwide are investing heavily in wind, solar, hydroelectric, and other renewable technologies. This energy revolution presents both remarkable opportunities and formidable challenges that will shape our civilization for generations to come. Solar power has experienced perhaps the most dramatic progress, with the cost of photovoltaic panels declining by approximately ninety percent over the past decade. This stunning price reduction has made solar competitive with or cheaper than fossil fuels in many regions, driving explosive growth in installations. Modern solar farms can generate hundreds of megawatts of power, while rooftop panels allow individual homeowners to produce their own electricity. However, solar energy faces the fundamental challenge of intermittency, since panels produce nothing at night and significantly less on cloudy days. Wind power has similarly matured into a major energy source, with modern turbines reaching heights of over two hundred meters and blade spans exceeding one hundred meters. Offshore wind farms, though more expensive to build, can access stronger and more consistent winds while avoiding some of the land-use conflicts that onshore installations sometimes create. Like solar, wind energy is intermittent and location-dependent, with the best resources often far from population centers requiring significant transmission infrastructure. The intermittency challenge has spurred intensive research into energy storage technologies. Lithium-ion batteries, the same technology powering electric vehicles and smartphones, are being deployed at grid scale to store excess renewable generation for later use. Other approaches include pumped hydroelectric storage, compressed air systems, and emerging technologies like flow batteries and hydrogen production. These storage solutions are essential for achieving high penetrations of renewable energy while maintaining grid reliability. Grid integration represents another crucial challenge. Electrical grids were designed around large, controllable power plants that could adjust output to match demand. Incorporating variable renewable sources requires new approaches to grid management, including sophisticated forecasting, demand response programs that shift electricity consumption to match generation, and potentially fundamental restructuring of electricity markets. Smart grid technologies that use digital communications and automated control systems are enabling more flexible and responsive electrical networks. Despite these challenges, the momentum behind renewable energy appears unstoppable, driven by falling costs, improving technology, supportive policies, and growing public demand for clean energy.',
    wordCount: 385,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'environment', 'technology'],
  },
  {
    id: 'passage-a03',
    title: 'The Evolution of Written Language',
    levelBand: 'advanced',
    text: 'The development of writing systems represents one of humanity most transformative achievements, enabling the preservation and transmission of knowledge across time and space in ways that oral traditions could never accomplish. While spoken language evolved naturally over hundreds of thousands of years, writing is a technology that humans deliberately invented and refined, with the earliest known systems emerging independently in Mesopotamia, Egypt, and China around five thousand years ago. These ancient writing systems solved the same fundamental problem but in remarkably different ways. The earliest Mesopotamian writing, known as cuneiform, began as simple pictographic representations impressed into clay tablets with a reed stylus. Over centuries, these pictures became increasingly abstract and stylized, eventually representing syllables rather than whole words. Egyptian hieroglyphics followed a somewhat similar path but retained their pictorial character for religious and monumental purposes while developing more cursive scripts for everyday use. Chinese writing, in contrast, evolved along a different trajectory, with each character generally representing a complete morpheme or meaningful unit, resulting in a system requiring thousands of symbols for full literacy. The invention of alphabetic writing, which occurred only once in human history, represented a cognitive breakthrough of extraordinary significance. Scholars believe that the first alphabet was created by Semitic-speaking peoples in the ancient Near East, possibly influenced by Egyptian hieroglyphics. This system captured the insight that spoken language can be analyzed as a sequence of distinct sounds, and that a small set of symbols representing these sounds could spell virtually any word. The Phoenician alphabet spread throughout the Mediterranean, evolving into Greek, which added vowel letters, and subsequently into Latin, Cyrillic, Arabic, and numerous other writing systems used today. Writing dramatically altered human cognition and society. Unlike speech, which is ephemeral and tied to immediate context, written text creates a permanent record that can be studied, analyzed, and verified. This enabled the development of complex administrative systems, legal codes, and religious doctrines. The accumulation of written knowledge across generations accelerated technological and cultural progress far beyond what oral traditions could achieve. Writing also transformed thought itself, enabling new forms of reasoning, classification, and analysis that are difficult or impossible to sustain through speech alone. The technologies of writing have continued to evolve, from clay tablets to papyrus to parchment to paper to digital text, each innovation expanding access and transforming how we create, distribute, and consume written information. Today, billions of people communicate daily through writing, largely unaware that they are participating in a tradition only a few thousand years old.',
    wordCount: 407,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['history', 'language', 'communication'],
  },
  {
    id: 'passage-a04',
    title: 'Understanding Sleep Science',
    levelBand: 'advanced',
    text: 'Sleep, a state we spend approximately one-third of our lives experiencing, remains one of the most fascinating and somewhat mysterious aspects of human biology. Despite its apparent simplicity, sleep involves complex neurological processes that are essential for physical health, cognitive function, and emotional wellbeing. Modern sleep science has revealed that what seems like passive unconsciousness is actually a dynamic state during which the brain engages in critical maintenance and consolidation activities. Sleep occurs in cycles lasting roughly ninety minutes, each containing distinct stages characterized by different brain wave patterns, eye movements, and physiological changes. The cycle begins with light sleep stages, during which the brain produces slower waves and the body begins to relax. Deep sleep, or slow-wave sleep, follows, characterized by the slowest brain waves and the most profound physical restoration. Growth hormone release peaks during this stage, and the immune system is particularly active. Memory consolidation for factual information also occurs primarily during slow-wave sleep. Rapid eye movement, or REM, sleep presents a fascinating paradox: the brain becomes nearly as active as during waking, yet the body is essentially paralyzed through a mechanism that prevents us from acting out our dreams. REM sleep appears crucial for emotional processing, creative problem-solving, and the consolidation of procedural memories and skills. The ratio of deep sleep to REM sleep changes throughout the night, with more slow-wave sleep earlier and more REM sleep toward morning. Sleep deprivation, whether total or partial, has profound consequences that extend far beyond simple fatigue. Cognitive abilities including attention, working memory, and executive function decline significantly after even modest sleep loss. Emotional regulation becomes impaired, with increased irritability, anxiety, and susceptibility to stress. Chronic insufficient sleep has been linked to serious health problems including cardiovascular disease, diabetes, obesity, and weakened immune function. There is also growing evidence connecting poor sleep to neurodegenerative conditions like Alzheimer disease, possibly because sleep facilitates the clearance of toxic proteins from the brain. The circadian rhythm, our internal biological clock, plays a crucial role in regulating sleep timing and quality. This roughly twenty-four-hour cycle is synchronized primarily by light exposure, which explains why shift work and jet lag can be so disruptive. Blue light from electronic devices can suppress melatonin production and shift circadian timing, contributing to the widespread sleep problems in modern society. Understanding these mechanisms has led to practical recommendations for improving sleep, including maintaining consistent sleep schedules, optimizing sleep environments, and limiting evening light exposure.',
    wordCount: 404,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['science', 'health', 'biology'],
  },
  {
    id: 'passage-a05',
    title: 'Urbanization and Its Global Impact',
    levelBand: 'advanced',
    text: 'The movement of human populations from rural areas to cities represents one of the most profound demographic shifts in history, fundamentally reshaping societies, economies, and environments across the globe. In 1800, only about three percent of the world population lived in urban areas. Today, that figure exceeds fifty-five percent and is projected to reach nearly seventy percent by 2050. This unprecedented transformation has created both remarkable opportunities and significant challenges that will define the twenty-first century. Cities have historically served as engines of economic growth, innovation, and cultural development. The concentration of people and businesses creates dense networks of interaction that facilitate the exchange of ideas, the specialization of labor, and the efficient delivery of services. Urban areas typically offer better access to education, healthcare, and economic opportunities than rural regions, which is why people continue to migrate to cities despite often difficult living conditions. The most productive and innovative companies tend to cluster in urban centers, where they can access skilled workers, suppliers, and customers. However, rapid urbanization has placed enormous pressure on infrastructure, services, and natural resources. Many cities in developing countries have grown faster than their capacity to provide adequate housing, transportation, water, sanitation, and electricity. Informal settlements, often lacking basic services and legal recognition, house significant portions of urban populations in many regions. Traffic congestion, air pollution, and insufficient waste management affect quality of life and public health in cities worldwide. The environmental footprint of cities presents both challenges and opportunities. Urban areas concentrate resource consumption and waste generation, contributing significantly to greenhouse gas emissions and other environmental problems. Yet the density of cities also creates potential for efficiency. Well-designed public transportation can move many more people with less energy than private automobiles. Compact development can preserve natural areas and reduce the need for resource-intensive infrastructure. District heating and cooling systems can achieve efficiencies impossible in dispersed settlements. Urban planning and governance are critical in determining whether cities develop sustainably. Forward-thinking cities are investing in green infrastructure, renewable energy, circular economy initiatives, and climate adaptation measures. They are redesigning streets to prioritize pedestrians, cyclists, and public transit while creating more green spaces for recreation and environmental services. Digital technologies are enabling smarter management of urban systems, from traffic flow to energy grids to emergency response. The future of urbanization will significantly influence global sustainability, social equity, and human wellbeing.',
    wordCount: 388,
    license: 'user-authored',
    sourceAttribution: 'Original composition for educational purposes',
    tags: ['geography', 'society', 'environment'],
  },
]

// ============================================================================
// EXPANDED WORD LISTS - 8 per level band with categories
// ============================================================================

export const EXPANDED_WORD_LISTS = [
  // BEGINNER - High Frequency
  {
    id: 'wl-b-hf1',
    title: 'High Frequency Words Set 1',
    levelBand: 'beginner',
    category: 'high-frequency',
    words: ['the', 'and', 'a', 'to', 'in', 'is', 'it', 'you', 'that', 'he', 'was', 'for', 'on', 'are', 'with', 'as', 'I', 'his', 'they', 'be', 'at', 'one', 'have', 'this', 'from', 'or', 'had', 'by', 'not', 'but', 'what', 'all', 'were', 'we', 'when', 'your', 'can', 'said', 'there', 'use'],
    license: 'public-domain',
  },
  // BEGINNER - CVC Words
  {
    id: 'wl-b-cvc1',
    title: 'CVC Words (Short A)',
    levelBand: 'beginner',
    category: 'decodable-cvc',
    words: ['cat', 'bat', 'hat', 'mat', 'sat', 'rat', 'pat', 'fat', 'can', 'man', 'pan', 'ran', 'tan', 'van', 'fan', 'ban', 'cap', 'map', 'nap', 'tap', 'gap', 'lap', 'sap', 'zap', 'bag', 'tag', 'rag', 'wag', 'nag', 'gag', 'bad', 'dad', 'had', 'mad', 'sad', 'pad', 'lad', 'cab', 'dab', 'jab'],
    license: 'public-domain',
  },
  {
    id: 'wl-b-cvc2',
    title: 'CVC Words (Short I/O)',
    levelBand: 'beginner',
    category: 'decodable-cvc',
    words: ['bit', 'fit', 'hit', 'kit', 'sit', 'pit', 'wit', 'big', 'dig', 'fig', 'jig', 'pig', 'rig', 'wig', 'bin', 'din', 'fin', 'pin', 'tin', 'win', 'cot', 'dot', 'got', 'hot', 'lot', 'not', 'pot', 'rot', 'top', 'hop', 'mop', 'pop', 'cop', 'dog', 'fog', 'hog', 'jog', 'log', 'bog', 'cob'],
    license: 'public-domain',
  },
  // BEGINNER - Confusables
  {
    id: 'wl-b-conf1',
    title: 'Confusable Letters (b/d/p)',
    levelBand: 'beginner',
    category: 'confusables',
    words: ['bad', 'dad', 'pad', 'bed', 'beg', 'peg', 'big', 'dig', 'pig', 'bid', 'did', 'bob', 'dob', 'pod', 'bud', 'dud', 'pub', 'dub', 'rub', 'tub', 'bop', 'pop', 'top', 'nod', 'bod', 'dot', 'pot', 'bot', 'dip', 'pip', 'tip', 'sip', 'nip', 'rip', 'zip', 'hip', 'lip', 'bit', 'pit', 'dit'],
    license: 'public-domain',
  },

  // ELEMENTARY - CVCC/CCVC
  {
    id: 'wl-e-blend1',
    title: 'Initial Consonant Blends',
    levelBand: 'elementary',
    category: 'decodable-cvcc',
    words: ['stop', 'step', 'stem', 'skip', 'skin', 'skit', 'spin', 'spot', 'spit', 'snap', 'snip', 'snob', 'swim', 'swam', 'swing', 'twin', 'trap', 'trip', 'trim', 'tree', 'from', 'frog', 'free', 'grip', 'grin', 'grab', 'glad', 'plan', 'plum', 'plot', 'clap', 'clip', 'club', 'crab', 'crop', 'drum', 'drip', 'drop', 'drag', 'brick'],
    license: 'public-domain',
  },
  {
    id: 'wl-e-blend2',
    title: 'Final Consonant Blends',
    levelBand: 'elementary',
    category: 'decodable-cvcc',
    words: ['help', 'held', 'belt', 'melt', 'felt', 'self', 'milk', 'silk', 'bulk', 'sulk', 'desk', 'risk', 'dusk', 'tusk', 'mask', 'task', 'crisp', 'clasp', 'grasp', 'trust', 'frost', 'twist', 'swift', 'drift', 'craft', 'draft', 'shaft', 'theft', 'shelf', 'tempt', 'stomp', 'stamp', 'clamp', 'cramp', 'bump', 'dump', 'hump', 'jump', 'lump', 'pump'],
    license: 'public-domain',
  },
  // ELEMENTARY - Digraphs
  {
    id: 'wl-e-digraph1',
    title: 'Consonant Digraphs',
    levelBand: 'elementary',
    category: 'digraphs',
    words: ['chat', 'chip', 'chop', 'chin', 'check', 'chess', 'chest', 'chick', 'child', 'chill', 'shop', 'ship', 'shed', 'shell', 'shelf', 'shift', 'sheet', 'shark', 'share', 'sharp', 'that', 'them', 'then', 'this', 'thin', 'thick', 'thing', 'think', 'thank', 'three', 'what', 'when', 'where', 'which', 'white', 'while', 'wheel', 'wheat', 'whisper', 'whistle'],
    license: 'public-domain',
  },
  // ELEMENTARY - Confusables
  {
    id: 'wl-e-conf1',
    title: 'Easily Confused Words',
    levelBand: 'elementary',
    category: 'confusables',
    words: ['was', 'saw', 'want', 'went', 'from', 'form', 'them', 'then', 'there', 'their', 'where', 'were', 'quiet', 'quite', 'tired', 'tried', 'angel', 'angle', 'dairy', 'diary', 'through', 'though', 'thought', 'brought', 'bought', 'caught', 'taught', 'should', 'would', 'could', 'accept', 'except', 'affect', 'effect', 'loose', 'lose', 'whose', 'who', 'witch', 'which'],
    license: 'public-domain',
  },

  // INTERMEDIATE - Vowel Teams
  {
    id: 'wl-i-vowel1',
    title: 'Vowel Team Words',
    levelBand: 'intermediate',
    category: 'vowel-teams',
    words: ['train', 'brain', 'chain', 'drain', 'grain', 'plain', 'Spain', 'strain', 'explain', 'remain', 'team', 'dream', 'steam', 'stream', 'cream', 'scream', 'beach', 'reach', 'teach', 'peach', 'speak', 'sneak', 'squeak', 'coat', 'boat', 'goat', 'float', 'throat', 'approach', 'coach', 'night', 'light', 'bright', 'flight', 'knight', 'might', 'right', 'sight', 'tight', 'slight'],
    license: 'public-domain',
  },
  // INTERMEDIATE - Morphology
  {
    id: 'wl-i-morph1',
    title: 'Common Prefixes',
    levelBand: 'intermediate',
    category: 'morphology',
    words: ['unable', 'unclear', 'unfair', 'unkind', 'unlock', 'redo', 'reread', 'rewrite', 'return', 'review', 'preview', 'predict', 'prepare', 'preschool', 'prefix', 'disagree', 'dislike', 'disappear', 'discover', 'disconnect', 'misuse', 'misplace', 'mislead', 'mistake', 'misbehave', 'nonfiction', 'nonsense', 'nonprofit', 'invisible', 'incorrect', 'incomplete', 'impossible', 'impatient', 'improper', 'impolite', 'overload', 'overlook', 'overcome', 'overnight', 'overseas'],
    license: 'public-domain',
  },
  {
    id: 'wl-i-morph2',
    title: 'Common Suffixes',
    levelBand: 'intermediate',
    category: 'morphology',
    words: ['helpful', 'thankful', 'careful', 'beautiful', 'wonderful', 'hopeless', 'careless', 'homeless', 'harmless', 'fearless', 'darkness', 'kindness', 'sadness', 'happiness', 'goodness', 'teacher', 'player', 'worker', 'farmer', 'singer', 'comfortable', 'enjoyable', 'reasonable', 'valuable', 'available', 'development', 'government', 'environment', 'entertainment', 'improvement', 'action', 'direction', 'protection', 'collection', 'connection', 'curious', 'serious', 'nervous', 'generous', 'dangerous'],
    license: 'public-domain',
  },
  // INTERMEDIATE - Confusables
  {
    id: 'wl-i-conf1',
    title: 'Advanced Confusable Pairs',
    levelBand: 'intermediate',
    category: 'confusables',
    words: ['advice', 'advise', 'device', 'devise', 'practice', 'practise', 'license', 'licence', 'principal', 'principle', 'stationary', 'stationery', 'complement', 'compliment', 'conscience', 'conscious', 'desert', 'dessert', 'personal', 'personnel', 'precede', 'proceed', 'emigrate', 'immigrate', 'elicit', 'illicit', 'eminent', 'imminent', 'ensure', 'insure', 'assure', 'allusion', 'illusion', 'delusion', 'discreet', 'discrete', 'formally', 'formerly', 'historic', 'historical'],
    license: 'public-domain',
  },

  // ADVANCED - Academic Vocabulary
  {
    id: 'wl-a-acad1',
    title: 'Academic Vocabulary Set 1',
    levelBand: 'advanced',
    category: 'academic',
    words: ['analyze', 'synthesize', 'evaluate', 'hypothesis', 'methodology', 'empirical', 'theoretical', 'paradigm', 'phenomena', 'correlation', 'causation', 'inference', 'deduction', 'induction', 'criterion', 'criteria', 'assumption', 'implication', 'interpretation', 'perspective', 'conceptual', 'framework', 'significant', 'substantial', 'comprehensive', 'fundamental', 'contemporary', 'subsequent', 'preliminary', 'predominant', 'corresponding', 'proportion', 'distribution', 'differentiate', 'distinguish', 'characterize', 'constitute', 'demonstrate', 'facilitate', 'incorporate'],
    license: 'public-domain',
  },
  {
    id: 'wl-a-acad2',
    title: 'Academic Vocabulary Set 2',
    levelBand: 'advanced',
    category: 'academic',
    words: ['acknowledge', 'acquisition', 'adaptation', 'alternative', 'amendment', 'appreciation', 'approximation', 'circumstance', 'clarification', 'classification', 'collaboration', 'compensation', 'complexity', 'concentration', 'configuration', 'consideration', 'consolidation', 'controversial', 'correspondence', 'deterioration', 'differentiation', 'discrimination', 'diversification', 'documentation', 'elaboration', 'enhancement', 'equivalent', 'exploitation', 'fluctuation', 'generalization', 'implementation', 'inconsistency', 'infrastructure', 'justification', 'manifestation', 'modification', 'negotiation', 'nonetheless', 'notwithstanding', 'participation'],
    license: 'public-domain',
  },
  // ADVANCED - Morphology
  {
    id: 'wl-a-morph1',
    title: 'Greek and Latin Roots',
    levelBand: 'advanced',
    category: 'morphology',
    words: ['autobiography', 'bibliography', 'biography', 'chronological', 'synchronize', 'democracy', 'demographic', 'epidemic', 'pandemic', 'empathy', 'sympathy', 'apathy', 'antipathy', 'telepathy', 'geography', 'geology', 'geometry', 'geophysics', 'hydrate', 'hydroelectric', 'hydraulic', 'dehydrate', 'microscope', 'telescope', 'periscope', 'stethoscope', 'philosophy', 'philanthropy', 'photosynthesis', 'photograph', 'psychology', 'psychiatry', 'psychoanalysis', 'telephone', 'telegraph', 'television', 'telecommunication', 'theology', 'theoretical', 'therapeutic'],
    license: 'public-domain',
  },
  // ADVANCED - Confusables
  {
    id: 'wl-a-conf1',
    title: 'Sophisticated Confusables',
    levelBand: 'advanced',
    category: 'confusables',
    words: ['allude', 'elude', 'allusion', 'illusion', 'ambiguous', 'ambivalent', 'amoral', 'immoral', 'appraise', 'apprise', 'censure', 'censor', 'climactic', 'climatic', 'complacent', 'complaisant', 'continual', 'continuous', 'credible', 'credulous', 'definite', 'definitive', 'deprecate', 'depreciate', 'disinterested', 'uninterested', 'endemic', 'epidemic', 'equitable', 'equable', 'exceptionable', 'exceptional', 'expedient', 'expeditious', 'explicable', 'explicit', 'fortuitous', 'fortunate', 'ingenious', 'ingenuous'],
    license: 'public-domain',
  },
]

// ============================================================================
// EXPANDED COMPREHENSION QUESTIONS
// ============================================================================

export const EXPANDED_COMPREHENSION_QUESTIONS = [
  // Questions for passage-b01 (The Red Ball)
  {
    id: 'comp-b01-1',
    passageId: 'passage-b01',
    prompt: 'What color was Sam\'s ball?',
    choices: ['Blue', 'Red', 'Green', 'Yellow'],
    correctChoiceIndex: 1,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The first sentence states "Sam had a red ball."',
  },
  {
    id: 'comp-b01-2',
    passageId: 'passage-b01',
    prompt: 'Where did Sam play with his ball?',
    choices: ['At school', 'In the park', 'In his house', 'At the beach'],
    correctChoiceIndex: 1,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage says Sam liked to play with the ball "in the park."',
  },
  {
    id: 'comp-b01-3',
    passageId: 'passage-b01',
    prompt: 'How did Sam feel when the ball went over the fence?',
    choices: ['Happy', 'Angry', 'Sad', 'Scared'],
    correctChoiceIndex: 2,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage states "Sam was sad" when the ball went over the fence.',
  },
  {
    id: 'comp-b01-4',
    passageId: 'passage-b01',
    prompt: 'Who found the ball?',
    choices: ['A cat', 'A kind dog', 'Sam\'s friend', 'Sam\'s mom'],
    correctChoiceIndex: 1,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage says "A kind dog found the ball."',
  },
  {
    id: 'comp-b01-5',
    passageId: 'passage-b01',
    prompt: 'What happened at the end of the story?',
    choices: ['Sam lost his ball again', 'Sam and the dog became friends', 'Sam went home', 'The dog ran away'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'sequence',
    explanation: 'The passage ends with Sam and the dog becoming good friends and playing every day.',
  },
  {
    id: 'comp-b01-6',
    passageId: 'passage-b01',
    prompt: 'Why do you think the dog is called "kind"?',
    choices: ['It is very cute', 'It helped Sam get his ball back', 'It has nice fur', 'It lives in the park'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'inferential',
    explanation: 'The dog showed kindness by bringing the ball back to Sam.',
  },

  // Questions for passage-e01 (The School Garden)
  {
    id: 'comp-e01-1',
    passageId: 'passage-e01',
    prompt: 'When did the class start the garden?',
    choices: ['In autumn', 'In winter', 'In spring', 'In summer'],
    correctChoiceIndex: 2,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage begins "Our class started a garden at school this spring."',
  },
  {
    id: 'comp-e01-2',
    passageId: 'passage-e01',
    prompt: 'What vegetable did the narrator choose to grow?',
    choices: ['Carrots', 'Beans', 'Tomatoes', 'Lettuce'],
    correctChoiceIndex: 2,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The narrator says "I picked tomatoes because they are my favorite."',
  },
  {
    id: 'comp-e01-3',
    passageId: 'passage-e01',
    prompt: 'What tasks did the students do every day?',
    choices: ['Planted seeds and dug holes', 'Watered plants and pulled weeds', 'Picked vegetables and cooked', 'Played and ate lunch'],
    correctChoiceIndex: 1,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage states "Every day, we watered our plants and pulled out the weeds."',
  },
  {
    id: 'comp-e01-4',
    passageId: 'passage-e01',
    prompt: 'What order did events happen in the story?',
    choices: ['Shared vegetables, planted seeds, pulled weeds', 'Planted seeds, pulled weeds, shared vegetables', 'Pulled weeds, planted seeds, shared vegetables', 'Shared vegetables, pulled weeds, planted seeds'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'sequence',
    explanation: 'The story follows the sequence: planting, caring for plants, then sharing the harvest.',
  },
  {
    id: 'comp-e01-5',
    passageId: 'passage-e01',
    prompt: 'Why did everyone say the vegetables tasted better than store ones?',
    choices: ['They were more expensive', 'They were grown by the students themselves', 'They had more salt', 'They were cooked differently'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'inferential',
    explanation: 'Things we grow ourselves often taste better because of the effort and care we put into them.',
  },
  {
    id: 'comp-e01-6',
    passageId: 'passage-e01',
    prompt: 'What does the word "sprouts" mean in this passage?',
    choices: ['Seeds', 'Weeds', 'Young plants just starting to grow', 'Fully grown vegetables'],
    correctChoiceIndex: 2,
    difficulty: 'intermediate',
    questionType: 'vocab',
    explanation: 'Sprouts are young plants that have just begun to grow from seeds.',
  },

  // Questions for passage-i01 (The Water Cycle)
  {
    id: 'comp-i01-1',
    passageId: 'passage-i01',
    prompt: 'What causes water to evaporate from oceans and lakes?',
    choices: ['The moon\'s gravity', 'Heat from the sun', 'Wind', 'Cold temperatures'],
    correctChoiceIndex: 1,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage states that "the sun heats water in oceans, lakes, and rivers, causing it to evaporate."',
  },
  {
    id: 'comp-i01-2',
    passageId: 'passage-i01',
    prompt: 'What forms when water vapor condenses in the atmosphere?',
    choices: ['Rain', 'Fog', 'Clouds', 'Snow'],
    correctChoiceIndex: 2,
    difficulty: 'easy',
    questionType: 'literal',
    explanation: 'The passage explains that condensed water vapor forms "tiny water droplets or ice crystals, forming clouds."',
  },
  {
    id: 'comp-i01-3',
    passageId: 'passage-i01',
    prompt: 'What is transpiration?',
    choices: ['Water evaporating from oceans', 'Plants releasing water through leaves', 'Rain falling from clouds', 'Water soaking into ground'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'vocab',
    explanation: 'Transpiration is defined as the process where plants "release some back into the air through their leaves."',
  },
  {
    id: 'comp-i01-4',
    passageId: 'passage-i01',
    prompt: 'What is the main idea of this passage?',
    choices: ['How clouds form', 'How rain helps plants grow', 'How water continuously moves around Earth', 'Why we should save water'],
    correctChoiceIndex: 2,
    difficulty: 'intermediate',
    questionType: 'main-idea',
    explanation: 'The main idea is that the water cycle continuously moves water around the planet in an endless loop.',
  },
  {
    id: 'comp-i01-5',
    passageId: 'passage-i01',
    prompt: 'Why does the author mention dinosaurs and ancient Rome?',
    choices: ['To make the topic more interesting', 'To show that the same water molecules have been recycled for billions of years', 'To explain how old Earth is', 'To discuss history'],
    correctChoiceIndex: 1,
    difficulty: 'hard',
    questionType: 'inferential',
    explanation: 'The author uses these examples to illustrate that the same water has been recycled countless times over billions of years.',
  },
  {
    id: 'comp-i01-6',
    passageId: 'passage-i01',
    prompt: 'What happens to water after it falls as precipitation?',
    choices: ['It all returns directly to the ocean', 'Some flows to rivers, some soaks into ground', 'It immediately evaporates again', 'It is all absorbed by plants'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'literal',
    explanation: 'The passage explains that some water "flows into streams and rivers" while "other water soaks into the ground."',
  },

  // Questions for passage-a01 (The Psychology of Decision Making)
  {
    id: 'comp-a01-1',
    passageId: 'passage-a01',
    prompt: 'What is confirmation bias?',
    choices: ['Seeking information that supports existing beliefs', 'Making decisions based on emotions', 'Preferring to avoid losses over gains', 'Feeling overwhelmed by too many choices'],
    correctChoiceIndex: 0,
    difficulty: 'intermediate',
    questionType: 'literal',
    explanation: 'The passage defines confirmation bias as the tendency to "seek out and remember information that supports existing beliefs."',
  },
  {
    id: 'comp-a01-2',
    passageId: 'passage-a01',
    prompt: 'According to the passage, why do many people fear airplane crashes more than car accidents?',
    choices: ['Airplane crashes are more deadly', 'The availability heuristic makes easily recalled events seem more likely', 'People have control when driving', 'News media exaggerates airplane dangers'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'literal',
    explanation: 'The passage explains this is due to the availability heuristic, which causes overestimation of easily recalled events.',
  },
  {
    id: 'comp-a01-3',
    passageId: 'passage-a01',
    prompt: 'What is the approximate ratio of pain from loss versus pleasure from gain?',
    choices: ['Equal', 'Loss is twice as painful', 'Gain is twice as pleasurable', 'Loss is three times as painful'],
    correctChoiceIndex: 1,
    difficulty: 'intermediate',
    questionType: 'literal',
    explanation: 'The passage states that "psychological pain of losing something is approximately twice as powerful as the pleasure of gaining."',
  },
  {
    id: 'comp-a01-4',
    passageId: 'passage-a01',
    prompt: 'What is "choice architecture"?',
    choices: ['The brain\'s decision-making structure', 'Designing buildings for better workflow', 'Structuring decisions to guide people toward beneficial outcomes', 'A type of cognitive bias'],
    correctChoiceIndex: 2,
    difficulty: 'hard',
    questionType: 'vocab',
    explanation: 'Choice architecture is defined as "structuring decisions to guide people toward beneficial outcomes."',
  },
  {
    id: 'comp-a01-5',
    passageId: 'passage-a01',
    prompt: 'What is the main argument of this passage?',
    choices: ['Humans are completely irrational', 'Understanding our cognitive biases can help us make better decisions', 'Emotions should be ignored in decision-making', 'Traditional economic theory is correct'],
    correctChoiceIndex: 1,
    difficulty: 'hard',
    questionType: 'main-idea',
    explanation: 'The passage argues that while we cannot achieve perfect rationality, awareness of our biases can improve decision-making.',
  },
  {
    id: 'comp-a01-6',
    passageId: 'passage-a01',
    prompt: 'What inference can be made about important decisions made when hungry or tired?',
    choices: ['They are usually better decisions', 'They are likely to be more impulsive and less controlled', 'They are not affected by physical state', 'They benefit from reduced overthinking'],
    correctChoiceIndex: 1,
    difficulty: 'hard',
    questionType: 'inferential',
    explanation: 'The passage states that hunger, fatigue, and stress "impair decision-making ability, leading to more impulsive choices."',
  },
]
