export type DeploymentEnv = 'production' | 'preview' | 'development';

function normalizeBaseUrl(value: string): string {
  return value.replace(/\/+$/, '');
}

function resolveDeploymentEnv(): DeploymentEnv {
  const vercelEnv = process.env.VERCEL_ENV as DeploymentEnv | undefined;
  if (vercelEnv) return vercelEnv;
  return process.env.NODE_ENV === 'production' ? 'production' : 'development';
}

export const DEPLOYMENT_ENV: DeploymentEnv = resolveDeploymentEnv();
export const IS_PUBLIC_DEPLOYMENT = DEPLOYMENT_ENV === 'production';

function resolveSiteUrl(): string {
  const explicit = process.env.NEXT_PUBLIC_SITE_URL;
  if (explicit) return normalizeBaseUrl(explicit);

  // In production, never fall back to Vercel's autogenerated domain.
  if (IS_PUBLIC_DEPLOYMENT) return 'https://neurobreath.co.uk';

  // Preview deployments should use their own URL so metadataBase/canonicals are correct.
  const vercelUrl = process.env.VERCEL_URL;
  if (vercelUrl) return `https://${normalizeBaseUrl(vercelUrl)}`;

  // Local/dev fallback.
  const port = process.env.PORT ?? '3000';
  return `http://localhost:${port}`;
}

export const SITE_URL = resolveSiteUrl();
export const LOCALES = ['uk', 'us'] as const;
export type LocaleKey = (typeof LOCALES)[number];

export const LOCALE_CONFIG: Record<LocaleKey, { language: string; locale: string }> = {
  uk: { language: 'en-GB', locale: 'en_GB' },
  us: { language: 'en-US', locale: 'en_US' },
};

export const DEFAULT_LOCALE: LocaleKey = 'uk';
