/**
 * Content for journey: new-to-adhd
 * Generated by scaffold-journey.mjs
 * 
 * Edit this file to customize copy while maintaining UK/US variants.
 * Source of truth for journey content across both regions.
 */

export interface JourneyContent {
  title: string;
  description: string;
  steps: Array<{
    title: string;
    summary: string;
    keyActions: string[];
    suggestedTools?: string[];
    suggestedGuides?: string[];
    faq?: Array<{
      q: string;
      a: string;
    }>;
  }>;
  completion: {
    title: string;
    summary: string;
    nextSteps: Array<{
      title: string;
      link: string;
      description: string;
    }>;
  };
}

// Journey metadata
export const journey = {
  id: 'new-to-adhd',
  slug: 'new-to-adhd',
  audience: ["adult"],
  primaryConditions: ["new"],
  estimatedMinutes: 20,
  steps: [{"stepId":"step-1","titleUK":"First Steps","titleUS":"First Steps","summaryUK":"Begin your journey","summaryUS":"Begin your journey","keyActions":["Learn the basics","Identify your needs","Set goals"],"suggestedTools":[],"suggestedGuides":[]},{"stepId":"step-2","titleUK":"Building Understanding","titleUS":"Building Understanding","summaryUK":"Deepen your knowledge","summaryUS":"Deepen your knowledge","keyActions":["Explore strategies","Try new approaches","Reflect on progress"],"suggestedTools":[],"suggestedGuides":[]},{"stepId":"step-3","titleUK":"Moving Forward","titleUS":"Moving Forward","summaryUK":"Plan for continued growth","summaryUS":"Plan for continued growth","keyActions":["Create routines","Build resilience","Celebrate wins"],"suggestedTools":[],"suggestedGuides":[]}],
  
  uk: {
    title: `Journey: new-to-adhd`,
    description: `A guided journey for new-to-adhd`,
    steps: [{"title":"First Steps","summary":"Begin your journey","keyActions":["Learn the basics","Identify your needs","Set goals"],"suggestedTools":[],"suggestedGuides":[]},{"title":"Building Understanding","summary":"Deepen your knowledge","keyActions":["Explore strategies","Try new approaches","Reflect on progress"],"suggestedTools":[],"suggestedGuides":[]},{"title":"Moving Forward","summary":"Plan for continued growth","keyActions":["Create routines","Build resilience","Celebrate wins"],"suggestedTools":[],"suggestedGuides":[]}],
    completion: {
      title: `Journey Complete`,
      summary: `You've taken important first steps`,
      nextSteps: [{"title":"Explore Tools","link":"/uk/tools","description":"Try practical tools"},{"title":"Read Guides","link":"/uk/guides","description":"Deepen your understanding"},{"title":"Get Help","link":"/uk/help-me-choose","description":"Find personalised recommendations"}],
    },
  } as JourneyContent,
  
  us: {
    title: `Journey: new-to-adhd`,
    description: `A guided journey for new-to-adhd`,
    steps: [{"title":"First Steps","summary":"Begin your journey","keyActions":["Learn the basics","Identify your needs","Set goals"],"suggestedTools":[],"suggestedGuides":[]},{"title":"Building Understanding","summary":"Deepen your knowledge","keyActions":["Explore strategies","Try new approaches","Reflect on progress"],"suggestedTools":[],"suggestedGuides":[]},{"title":"Moving Forward","summary":"Plan for continued growth","keyActions":["Create routines","Build resilience","Celebrate wins"],"suggestedTools":[],"suggestedGuides":[]}],
    completion: {
      title: `Journey Complete`,
      summary: `You've taken important first steps`,
      nextSteps: [{"title":"Explore Tools","link":"/us/tools","description":"Try practical tools"},{"title":"Read Guides","link":"/us/guides","description":"Deepen your understanding"},{"title":"Get Help","link":"/us/help-me-choose","description":"Find personalized recommendations"}],
    },
  } as JourneyContent,
};
