import type { EvidenceSource } from './types';

export type { EvidenceSource } from './types';

export const evidenceSources: Record<string, EvidenceSource> = {
  nice_ng87: {
    id: 'nice_ng87',
    title: 'Attention deficit hyperactivity disorder: diagnosis and management (NG87)',
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/ng87',
    region: 'UK',
    contentType: 'guidance',
    lastChecked: '2026-01-16',
  },
  nhs_adhd: {
    id: 'nhs_adhd',
    title: 'Attention deficit hyperactivity disorder (ADHD)',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/conditions/attention-deficit-hyperactivity-disorder-adhd/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nice_cg128: {
    id: 'nice_cg128',
    title: 'Autism spectrum disorder in under 19s: recognition, referral and diagnosis (CG128)',
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/cg128',
    region: 'UK',
    contentType: 'guidance',
    lastChecked: '2026-01-16',
  },
  nice_cg142: {
    id: 'nice_cg142',
    title: 'Autism spectrum disorder in adults: diagnosis and management (CG142)',
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/cg142',
    region: 'UK',
    contentType: 'guidance',
    lastChecked: '2026-01-16',
  },
  nhs_autism: {
    id: 'nhs_autism',
    title: 'Autism',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/conditions/autism/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nhs_breathing_stress: {
    id: 'nhs_breathing_stress',
    title: 'Breathing exercises for stress',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/mental-health/self-help/guides-tools-and-activities/breathing-exercises-for-stress/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nice_cg113: {
    id: 'nice_cg113',
    title: 'Generalised anxiety disorder and panic disorder in adults (CG113)',
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/cg113',
    region: 'UK',
    contentType: 'guidance',
    lastChecked: '2026-01-16',
  },
  nhs_gad: {
    id: 'nhs_gad',
    title: 'Generalised anxiety disorder',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/mental-health/conditions/generalised-anxiety-disorder/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nice_ng222: {
    id: 'nice_ng222',
    title: 'Depression in adults: treatment and management (NG222)',
    publisher: 'NICE',
    url: 'https://www.nice.org.uk/guidance/ng222',
    region: 'UK',
    contentType: 'guidance',
    lastChecked: '2026-01-16',
  },
  nhs_depression: {
    id: 'nhs_depression',
    title: 'Clinical depression',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/mental-health/conditions/clinical-depression/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nhs_insomnia: {
    id: 'nhs_insomnia',
    title: 'Insomnia',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/conditions/insomnia/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nhs_dyslexia: {
    id: 'nhs_dyslexia',
    title: 'Dyslexia',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/conditions/dyslexia/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  rose_review_2009: {
    id: 'rose_review_2009',
    title: 'Independent review of the teaching of early reading (Rose Review)',
    publisher: 'Department for Children, Schools and Families',
    url: 'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/284736/independent_review_reading_final_report.pdf',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  pubmed_31411903: {
    id: 'pubmed_31411903',
    title: 'Comparative efficacy and tolerability of ADHD medications (PMID 31411903)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31411903/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_10517495: {
    id: 'pubmed_10517495',
    title: 'MTA Cooperative Group multimodal treatment study (PMID 10517495)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/10517495/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_28545751: {
    id: 'pubmed_28545751',
    title: 'Evidence-based approaches to autism (PMID 28545751)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28545751/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_29616846: {
    id: 'pubmed_29616846',
    title: 'Breath-control and slow breathing review (PMID 29616846)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/29616846/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_28974862: {
    id: 'pubmed_28974862',
    title: 'Deep breathing and stress physiology (PMID 28974862)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28974862/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_11744522: {
    id: 'pubmed_11744522',
    title: 'Breathing rate and heart rate variability (PMID 11744522)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/11744522/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_30301513: {
    id: 'pubmed_30301513',
    title: 'Exercise and anxiety review (PMID 30301513)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/30301513/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_16551270: {
    id: 'pubmed_16551270',
    title: 'STAR*D trial outcomes (PMID 16551270)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/16551270/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_27470975: {
    id: 'pubmed_27470975',
    title: 'Behavioural activation for depression review (PMID 27470975)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/27470975/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_26447429: {
    id: 'pubmed_26447429',
    title: 'CBT-I for insomnia review (PMID 26447429)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/26447429/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  pubmed_25638728: {
    id: 'pubmed_25638728',
    title: 'Developmental dyslexia review (PMID 25638728)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/25638728/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-16',
  },
  cdc_stress: {
    id: 'cdc_stress',
    title: 'Stress and coping',
    publisher: 'CDC',
    url: 'https://www.cdc.gov/mentalhealth/stress-coping/index.html',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nih_sleep: {
    id: 'nih_sleep',
    title: 'Sleep and sleep disorders',
    publisher: 'NIH',
    url: 'https://www.nhlbi.nih.gov/health/sleep',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nimh_adhd: {
    id: 'nimh_adhd',
    title: 'ADHD information',
    publisher: 'NIMH',
    url: 'https://www.nimh.nih.gov/health/topics/attention-deficit-hyperactivity-disorder-adhd',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  medlineplus_anxiety: {
    id: 'medlineplus_anxiety',
    title: 'Anxiety',
    publisher: 'MedlinePlus',
    url: 'https://medlineplus.gov/anxiety.html',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  medlineplus_depression: {
    id: 'medlineplus_depression',
    title: 'Depression',
    publisher: 'MedlinePlus',
    url: 'https://medlineplus.gov/depression.html',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  cdc_autism: {
    id: 'cdc_autism',
    title: 'Autism spectrum disorder',
    publisher: 'CDC',
    url: 'https://www.cdc.gov/autism/index.html',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  cdc_dyslexia: {
    id: 'cdc_dyslexia',
    title: 'Learning disabilities',
    publisher: 'CDC',
    url: 'https://www.cdc.gov/ncbddd/childdevelopment/learning-disorder.html',
    region: 'US',
    contentType: 'reference',
    lastChecked: '2026-01-16',
  },
  nhs_inform_grounding: {
    id: 'nhs_inform_grounding',
    title: 'Grounding exercises',
    publisher: 'NHS inform',
    url: 'https://www.nhsinform.scot/healthy-living/mental-wellbeing/breathing-and-relaxation-exercises/grounding-exercises/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-28',
  },
  nhs_mindfulness: {
    id: 'nhs_mindfulness',
    title: 'Mindfulness',
    publisher: 'NHS',
    url: 'https://www.nhs.uk/mental-health/self-help/tips-and-support/mindfulness/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-28',
  },
  nhs_every_mind_matters_meditation: {
    id: 'nhs_every_mind_matters_meditation',
    title: 'How to meditate for beginners',
    publisher: 'NHS Every Mind Matters',
    url: 'https://www.nhs.uk/every-mind-matters/mental-wellbeing-tips/how-to-meditate-for-beginners/',
    region: 'UK',
    contentType: 'reference',
    lastChecked: '2026-01-28',
  },
  pubmed_body_scan_2022: {
    id: 'pubmed_body_scan_2022',
    title: 'Body scan meditation for stress reduction (PMID 35538557)',
    publisher: 'PubMed',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35538557/',
    region: 'GLOBAL',
    contentType: 'article',
    lastChecked: '2026-01-28',
  },
};
