'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Download, X } from 'lucide-react';
import { toast } from 'sonner';

interface NowNextBuilderProps {
  onComplete?: () => void;
}

export function NowNextBuilder({ onComplete }: NowNextBuilderProps) {
  const [nowActivity, setNowActivity] = useState('');
  const [nextActivity, setNextActivity] = useState('');
  const [fontSize, setFontSize] = useState(48);

  const handleExport = () => {
    if (!nowActivity || !nextActivity) {
      toast.error('Please fill in both activities');
      return;
    }

    // Create a simple text version
    const content = `NOW/NEXT BOARD

${'='.repeat(50)}

NOW
${nowActivity}

${'='.repeat(50)}

NEXT
${nextActivity}

${'='.repeat(50)}

Generated by NeuroBreath Autism Hub
Visual supports help with transitions
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `now-next-board-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    // Track usage
    const toolsCreated = parseInt(localStorage.getItem('nb:autism:v2:toolsCreated') || '0');
    localStorage.setItem('nb:autism:v2:toolsCreated', String(toolsCreated + 1));

    if (toolsCreated === 2) {
      toast.success('🎯 Badge Earned: Toolkit Builder!', {
        description: 'You created 3 different tools'
      });
    } else {
      toast.success('Now/Next board exported!');
    }

    onComplete?.();
  };

  const handleClear = () => {
    setNowActivity('');
    setNextActivity('');
  };

  return (
    <Card className="border-2 border-orange-200 dark:border-orange-900">
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle>Now/Next Builder</CardTitle>
            <CardDescription>
              Create a visual schedule for transitions • Evidence: NICE CG170
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Input Section */}
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="now">What's happening NOW?</Label>
            <Input
              id="now"
              value={nowActivity}
              onChange={(e) => setNowActivity(e.target.value)}
              placeholder="e.g., Snack time"
              className="text-lg"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="next">What's happening NEXT?</Label>
            <Input
              id="next"
              value={nextActivity}
              onChange={(e) => setNextActivity(e.target.value)}
              placeholder="e.g., Story time"
              className="text-lg"
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="fontSize">Text Size: {fontSize}px</Label>
            <input
              id="fontSize"
              type="range"
              min="24"
              max="72"
              value={fontSize}
              onChange={(e) => setFontSize(parseInt(e.target.value))}
              className="w-full"
              aria-label="Text size slider"
            />
          </div>
        </div>

        {/* Preview */}
        <div className="flex flex-col md:flex-row gap-4">
          <div className="flex-1 border-4 border-blue-500 rounded-lg p-6 bg-blue-50 dark:bg-blue-950/20 text-center min-h-[200px] flex flex-col items-center justify-center">
            <div className="text-blue-700 dark:text-blue-300 font-bold text-xl mb-4">NOW</div>
            {/* eslint-disable-next-line react/forbid-dom-props */}
            <div 
              className="font-semibold break-words" 
              style={{ fontSize: `${fontSize}px`, color: 'rgb(30 58 138)' }}
            >
              {nowActivity || '???'}
            </div>
          </div>

          <div className="flex-1 border-4 border-green-500 rounded-lg p-6 bg-green-50 dark:bg-green-950/20 text-center min-h-[200px] flex flex-col items-center justify-center relative">
            <div className="absolute top-2 left-2 text-4xl">➡️</div>
            <div className="text-green-700 dark:text-green-300 font-bold text-xl mb-4">NEXT</div>
            {/* eslint-disable-next-line react/forbid-dom-props */}
            <div 
              className="font-semibold break-words" 
              style={{ fontSize: `${fontSize}px`, color: 'rgb(20 83 45)' }}
            >
              {nextActivity || '???'}
            </div>
          </div>
        </div>

        {/* Action Buttons */}
        <div className="flex gap-3">
          <Button onClick={handleExport} className="flex-1">
            <Download className="mr-2 h-4 w-4" />
            Export Board
          </Button>
          <Button onClick={handleClear} variant="outline">
            <X className="mr-2 h-4 w-4" />
            Clear
          </Button>
        </div>

        <div className="text-xs text-muted-foreground">
          <strong>How to use:</strong> Print this board and display it where visible. Update before each transition. Point to "NOW" then "NEXT" when giving warnings.
        </div>
      </CardContent>
    </Card>
  );
}
