'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Checkbox } from '@/components/ui/checkbox';
import { Label } from '@/components/ui/label';
import { Separator } from '@/components/ui/separator';
import { Download, RefreshCw, Sparkles } from 'lucide-react';
import { toast } from 'sonner';

interface SensoryItem {
  id: string;
  label: string;
  category: 'seeking' | 'avoiding';
}

const sensoryItems: SensoryItem[] = [
  { id: 'loud-noises', label: 'Loud or unexpected noises', category: 'avoiding' },
  { id: 'bright-lights', label: 'Bright or fluorescent lights', category: 'avoiding' },
  { id: 'crowds', label: 'Crowded or busy spaces', category: 'avoiding' },
  { id: 'textures', label: 'Certain textures (clothing, food)', category: 'avoiding' },
  { id: 'smells', label: 'Strong smells', category: 'avoiding' },
  { id: 'movement', label: 'Seeks movement (spinning, rocking)', category: 'seeking' },
  { id: 'deep-pressure', label: 'Seeks deep pressure (hugs, squeezing)', category: 'seeking' },
  { id: 'oral-input', label: 'Seeks oral input (chewing, biting)', category: 'seeking' },
  { id: 'visual-stimming', label: 'Enjoys visual patterns or spinning objects', category: 'seeking' },
  { id: 'tactile-seeking', label: 'Seeks tactile input (touching everything)', category: 'seeking' }
];

interface SensoryDetectiveProps {
  onComplete?: () => void;
}

export function SensoryDetective({ onComplete }: SensoryDetectiveProps) {
  const [selected, setSelected] = useState<string[]>([]);
  const [showPlan, setShowPlan] = useState(false);

  const toggleItem = (id: string) => {
    setSelected(prev => 
      prev.includes(id) ? prev.filter(i => i !== id) : [...prev, id]
    );
  };

  const generatePlan = () => {
    if (selected.length === 0) {
      toast.error('Please select at least one sensory need');
      return;
    }
    setShowPlan(true);
  };

  const exportPlan = () => {
    const selectedItems = sensoryItems.filter(item => selected.includes(item.id));
    const avoiding = selectedItems.filter(i => i.category === 'avoiding');
    const seeking = selectedItems.filter(i => i.category === 'seeking');

    const content = `SENSORY PROFILE & PLAN
Generated: ${new Date().toLocaleDateString()}

${'='.repeat(50)}

SENSORY SENSITIVITIES (AVOIDING):
${avoiding.length > 0 ? avoiding.map(i => `• ${i.label}`).join('\n') : 'None identified'}

${'='.repeat(50)}

SENSORY SEEKING:
${seeking.length > 0 ? seeking.map(i => `• ${i.label}`).join('\n') : 'None identified'}

${'='.repeat(50)}

RECOMMENDED CALM CORNER ITEMS:

${avoiding.some(i => i.id === 'loud-noises') ? '• Noise-cancelling headphones or earplugs\n' : ''}${avoiding.some(i => i.id === 'bright-lights') ? '• Desk lamp or dimmer switch\n' : ''}${avoiding.some(i => i.id === 'crowds') ? '• Quiet space or corner with partition\n' : ''}${avoiding.some(i => i.id === 'textures') ? '• Soft blanket or preferred fabric\n' : ''}${avoiding.some(i => i.id === 'smells') ? '• Unscented products; personal fan\n' : ''}${seeking.some(i => i.id === 'movement') ? '• Wobble cushion or therapy ball\n' : ''}${seeking.some(i => i.id === 'deep-pressure') ? '• Weighted lap pad or compression vest\n' : ''}${seeking.some(i => i.id === 'oral-input') ? '• Chewelry or chewy snacks (pretzels, dried fruit)\n' : ''}${seeking.some(i => i.id === 'visual-stimming') ? '• Liquid timer or fidget spinner\n' : ''}${seeking.some(i => i.id === 'tactile-seeking') ? '• Fidget toys, therapy putty, textured items\n' : ''}
${'='.repeat(50)}

STRATEGIES:

1. REDUCE SENSORY OVERLOAD:
   - Minimize triggers identified above
   - Offer breaks before overwhelm
   - Create a "calm corner" with recommended items

2. PROVIDE SENSORY INPUT:
   - Offer sensory-seeking activities regularly
   - Use as a regulation tool, not a punishment
   - Schedule sensory breaks (10 min every 90 min)

3. TEACH SELF-ADVOCACY:
   - Help identify "I need a break" signals
   - Provide a break card (no explanation needed)
   - Practice asking for sensory tools

${'='.repeat(50)}

NEXT STEPS:
• Share this profile with school/workplace
• Gather recommended items for calm corner
• Monitor and adjust based on what helps

Evidence: NICE CG170 recommends sensory assessments
Generated by NeuroBreath Autism Hub
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `sensory-plan-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    // Track usage
    const toolsCreated = parseInt(localStorage.getItem('nb:autism:v2:toolsCreated') || '0');
    localStorage.setItem('nb:autism:v2:toolsCreated', String(toolsCreated + 1));

    if (toolsCreated === 2) {
      toast.success('🎯 Badge Earned: Toolkit Builder!', {
        description: 'You created 3 different tools'
      });
    } else {
      toast.success('Sensory plan exported!');
    }

    onComplete?.();
  };

  const reset = () => {
    setSelected([]);
    setShowPlan(false);
  };

  const selectedItems = sensoryItems.filter(item => selected.includes(item.id));
  const avoiding = selectedItems.filter(i => i.category === 'avoiding');
  const seeking = selectedItems.filter(i => i.category === 'seeking');

  return (
    <Card className="border-2 border-purple-200 dark:border-purple-900">
      <CardHeader>
        <div className="flex items-center gap-3">
          <Sparkles className="h-6 w-6 text-purple-600" />
          <div>
            <CardTitle>Sensory Detective</CardTitle>
            <CardDescription>
              Identify sensory needs and generate a personalized plan
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent className="space-y-6">
        {!showPlan ? (
          <>
            <div className="space-y-4">
              <div>
                <h3 className="font-semibold mb-3 text-red-700 dark:text-red-400">Sensory Sensitivities (Avoiding)</h3>
                <div className="space-y-2">
                  {sensoryItems.filter(i => i.category === 'avoiding').map(item => (
                    <div key={item.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={item.id}
                        checked={selected.includes(item.id)}
                        onCheckedChange={() => toggleItem(item.id)}
                      />
                      <Label htmlFor={item.id} className="cursor-pointer">{item.label}</Label>
                    </div>
                  ))}
                </div>
              </div>

              <Separator />

              <div>
                <h3 className="font-semibold mb-3 text-green-700 dark:text-green-400">Sensory Seeking</h3>
                <div className="space-y-2">
                  {sensoryItems.filter(i => i.category === 'seeking').map(item => (
                    <div key={item.id} className="flex items-center space-x-2">
                      <Checkbox
                        id={item.id}
                        checked={selected.includes(item.id)}
                        onCheckedChange={() => toggleItem(item.id)}
                      />
                      <Label htmlFor={item.id} className="cursor-pointer">{item.label}</Label>
                    </div>
                  ))}
                </div>
              </div>
            </div>

            <Button onClick={generatePlan} className="w-full" disabled={selected.length === 0}>
              Generate Sensory Plan
            </Button>
          </>
        ) : (
          <>
            <div className="space-y-4">
              {avoiding.length > 0 && (
                <div>
                  <h3 className="font-semibold mb-2 text-red-700 dark:text-red-400">Sensory Sensitivities (Avoiding)</h3>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    {avoiding.map(item => (
                      <li key={item.id}>{item.label}</li>
                    ))}
                  </ul>
                </div>
              )}

              {seeking.length > 0 && (
                <div>
                  <h3 className="font-semibold mb-2 text-green-700 dark:text-green-400">Sensory Seeking</h3>
                  <ul className="list-disc list-inside space-y-1 text-sm">
                    {seeking.map(item => (
                      <li key={item.id}>{item.label}</li>
                    ))}
                  </ul>
                </div>
              )}

              <Separator />

              <div>
                <h3 className="font-semibold mb-2">Recommended Calm Corner Items</h3>
                <ul className="list-disc list-inside space-y-1 text-sm text-muted-foreground">
                  {avoiding.some(i => i.id === 'loud-noises') && <li>Noise-cancelling headphones or earplugs</li>}
                  {avoiding.some(i => i.id === 'bright-lights') && <li>Desk lamp or dimmer switch</li>}
                  {avoiding.some(i => i.id === 'crowds') && <li>Quiet space or corner with partition</li>}
                  {avoiding.some(i => i.id === 'textures') && <li>Soft blanket or preferred fabric</li>}
                  {avoiding.some(i => i.id === 'smells') && <li>Unscented products; personal fan</li>}
                  {seeking.some(i => i.id === 'movement') && <li>Wobble cushion or therapy ball</li>}
                  {seeking.some(i => i.id === 'deep-pressure') && <li>Weighted lap pad or compression vest</li>}
                  {seeking.some(i => i.id === 'oral-input') && <li>Chewelry or chewy snacks</li>}
                  {seeking.some(i => i.id === 'visual-stimming') && <li>Liquid timer or fidget spinner</li>}
                  {seeking.some(i => i.id === 'tactile-seeking') && <li>Fidget toys, therapy putty, textured items</li>}
                </ul>
              </div>

              <div className="p-4 bg-blue-50 dark:bg-blue-950/20 rounded-lg">
                <h3 className="font-semibold mb-2">Key Strategies</h3>
                <ol className="list-decimal list-inside space-y-2 text-sm text-muted-foreground">
                  <li>Minimize sensory triggers identified above</li>
                  <li>Offer sensory breaks regularly (10 min every 90 min)</li>
                  <li>Provide sensory-seeking activities as regulation tools</li>
                  <li>Create a calm corner with recommended items</li>
                  <li>Teach self-advocacy: "I need a break"</li>
                </ol>
              </div>
            </div>

            <div className="flex gap-3">
              <Button onClick={exportPlan} className="flex-1">
                <Download className="mr-2 h-4 w-4" />
                Export Plan
              </Button>
              <Button onClick={reset} variant="outline">
                <RefreshCw className="mr-2 h-4 w-4" />
                Start Over
              </Button>
            </div>
          </>
        )}

        <div className="text-xs text-muted-foreground">
          Evidence: NICE CG170 recommends sensory assessments and environmental modifications
        </div>
      </CardContent>
    </Card>
  );
}
