'use client';

import { useState } from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Separator } from '@/components/ui/separator';
import { Target, Clock, TrendingUp, Download, Save, CheckCircle2, ArrowRight } from 'lucide-react';
import { 
  generateDailyPlan, 
  ageBandLabels, 
  mainNeedLabels, 
  settingLabels,
  type AgeBand,
  type MainNeed,
  type Setting,
  type DailyPlan
} from '@/lib/data/todays-plan';
import { toast } from 'sonner';

interface TodaysPlanWizardProps {
  onComplete?: () => void;
}

export function TodaysPlanWizard({ onComplete }: TodaysPlanWizardProps) {
  const [step, setStep] = useState<'config' | 'plan'>('config');
  const [ageBand, setAgeBand] = useState<AgeBand | ''>('');
  const [mainNeed, setMainNeed] = useState<MainNeed | ''>('');
  const [setting, setSetting] = useState<Setting | ''>('');
  const [generatedPlan, setGeneratedPlan] = useState<DailyPlan | null>(null);

  const canGenerate = ageBand && mainNeed && setting;

  const handleGenerate = () => {
    if (!canGenerate) return;

    const plan = generateDailyPlan({
      ageBand: ageBand as AgeBand,
      mainNeed: mainNeed as MainNeed,
      setting: setting as Setting
    });

    setGeneratedPlan(plan);
    setStep('plan');

    // Award badge for first plan
    const plansCreated = parseInt(localStorage.getItem('nb:autism:v2:plansCreated') || '0');
    localStorage.setItem('nb:autism:v2:plansCreated', String(plansCreated + 1));

    if (plansCreated === 0) {
      toast.success('🎯 Badge Earned: Plan Creator!', {
        description: 'You created your first Today\'s Plan'
      });
    }

    onComplete?.();
  };

  const handleSave = () => {
    const plans = JSON.parse(localStorage.getItem('nb:autism:v2:savedPlans') || '[]');
    plans.push({
      date: new Date().toISOString(),
      config: { ageBand, mainNeed, setting },
      plan: generatedPlan
    });
    localStorage.setItem('nb:autism:v2:savedPlans', JSON.stringify(plans));
    toast.success('Plan saved successfully!');
  };

  const handleExportPDF = () => {
    // Simple text export for now
    if (!generatedPlan) return;

    const content = `TODAY'S PLAN

Age Band: ${ageBandLabels[ageBand as AgeBand]}
Main Need: ${mainNeedLabels[mainNeed as MainNeed]}
Setting: ${settingLabels[setting as Setting]}
Generated: ${new Date().toLocaleDateString()}

${'='.repeat(50)}

DO NOW (Under 5 minutes each):

${generatedPlan.doNow.map((action, i) => `
${i + 1}. ${action.title}
   ${action.description}
   Duration: ${action.duration}
   ${action.evidence ? `Evidence: ${action.evidence}` : ''}`).join('\n')}

${'='.repeat(50)}

BUILD THIS WEEK:

${generatedPlan.buildThisWeek.map((action, i) => `
${i + 1}. ${action.title}
   ${action.description}
   Time: ${action.duration}
   ${action.evidence ? `Evidence: ${action.evidence}` : ''}`).join('\n')}

${'='.repeat(50)}

MEASUREMENT:

${generatedPlan.measurement.title}
${generatedPlan.measurement.description}

How to measure:
${generatedPlan.measurement.howTo}

${'='.repeat(50)}

Generated by NeuroBreath Autism Hub
Evidence-based strategies for autism support
`;

    const blob = new Blob([content], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `todays-plan-${new Date().toISOString().split('T')[0]}.txt`;
    a.click();
    URL.revokeObjectURL(url);

    toast.success('Plan exported successfully!');
  };

  const handleReset = () => {
    setStep('config');
    setAgeBand('');
    setMainNeed('');
    setSetting('');
    setGeneratedPlan(null);
  };

  return (
    <Card className="border-2 border-blue-200 dark:border-blue-900">
      <CardHeader>
        <div className="flex items-center gap-3">
          <Target className="h-8 w-8 text-blue-600" />
          <div>
            <CardTitle className="text-2xl">Today\'s Plan Wizard</CardTitle>
            <CardDescription>
              Generate a practical, evidence-based plan tailored to your situation
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        {step === 'config' && (
          <div className="space-y-6">
            <div className="space-y-2">
              <label className="text-sm font-medium">Age Band</label>
              <Select value={ageBand} onValueChange={(val) => setAgeBand(val as AgeBand)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select age band" />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(ageBandLabels).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Main Need Right Now</label>
              <Select value={mainNeed} onValueChange={(val) => setMainNeed(val as MainNeed)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select main need" />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(mainNeedLabels).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="space-y-2">
              <label className="text-sm font-medium">Setting</label>
              <Select value={setting} onValueChange={(val) => setSetting(val as Setting)}>
                <SelectTrigger>
                  <SelectValue placeholder="Select setting" />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(settingLabels).map(([key, label]) => (
                    <SelectItem key={key} value={key}>{label}</SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <Button 
              onClick={handleGenerate} 
              disabled={!canGenerate}
              className="w-full"
              size="lg"
            >
              Generate My Plan
              <ArrowRight className="ml-2 h-4 w-4" />
            </Button>
          </div>
        )}

        {step === 'plan' && generatedPlan && (
          <div className="space-y-6">
            {/* Config Summary */}
            <div className="flex flex-wrap gap-2">
              <Badge variant="secondary">{ageBandLabels[ageBand as AgeBand]}</Badge>
              <Badge variant="secondary">{mainNeedLabels[mainNeed as MainNeed]}</Badge>
              <Badge variant="secondary">{settingLabels[setting as Setting]}</Badge>
            </div>

            <Separator />

            {/* Do Now Section */}
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Clock className="h-5 w-5 text-green-600" />
                <h3 className="text-lg font-semibold">Do Now (Under 5 Minutes)</h3>
              </div>
              <div className="space-y-4">
                {generatedPlan.doNow.map((action, index) => (
                  <Card key={index} className="border-green-200 dark:border-green-900">
                    <CardContent className="pt-4">
                      <div className="flex gap-3">
                        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-green-100 dark:bg-green-900 flex items-center justify-center font-semibold text-green-700 dark:text-green-300">
                          {index + 1}
                        </div>
                        <div className="flex-1 space-y-2">
                          <h4 className="font-semibold">{action.title}</h4>
                          <p className="text-sm text-muted-foreground">{action.description}</p>
                          <div className="flex items-center gap-4 text-xs text-muted-foreground">
                            <span className="flex items-center gap-1">
                              <Clock className="h-3 w-3" />
                              {action.duration}
                            </span>
                            {action.evidence && (
                              <span className="flex items-center gap-1">
                                <CheckCircle2 className="h-3 w-3" />
                                {action.evidence}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>

            <Separator />

            {/* Build This Week Section */}
            <div>
              <div className="flex items-center gap-2 mb-4">
                <TrendingUp className="h-5 w-5 text-blue-600" />
                <h3 className="text-lg font-semibold">Build This Week</h3>
              </div>
              <div className="space-y-4">
                {generatedPlan.buildThisWeek.map((action, index) => (
                  <Card key={index} className="border-blue-200 dark:border-blue-900">
                    <CardContent className="pt-4">
                      <div className="flex gap-3">
                        <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-100 dark:bg-blue-900 flex items-center justify-center font-semibold text-blue-700 dark:text-blue-300">
                          {index + 1}
                        </div>
                        <div className="flex-1 space-y-2">
                          <h4 className="font-semibold">{action.title}</h4>
                          <p className="text-sm text-muted-foreground">{action.description}</p>
                          <div className="flex items-center gap-4 text-xs text-muted-foreground">
                            <span className="flex items-center gap-1">
                              <Clock className="h-3 w-3" />
                              {action.duration}
                            </span>
                            {action.evidence && (
                              <span className="flex items-center gap-1">
                                <CheckCircle2 className="h-3 w-3" />
                                {action.evidence}
                              </span>
                            )}
                          </div>
                        </div>
                      </div>
                    </CardContent>
                  </Card>
                ))}
              </div>
            </div>

            <Separator />

            {/* Measurement Section */}
            <div>
              <div className="flex items-center gap-2 mb-4">
                <Target className="h-5 w-5 text-purple-600" />
                <h3 className="text-lg font-semibold">Track Progress</h3>
              </div>
              <Card className="border-purple-200 dark:border-purple-900 bg-purple-50 dark:bg-purple-950/20">
                <CardContent className="pt-4 space-y-2">
                  <h4 className="font-semibold">{generatedPlan.measurement.title}</h4>
                  <p className="text-sm text-muted-foreground">{generatedPlan.measurement.description}</p>
                  <div className="mt-2 p-3 bg-white dark:bg-gray-900 rounded-md">
                    <p className="text-sm"><strong>How to measure:</strong></p>
                    <p className="text-sm text-muted-foreground mt-1">{generatedPlan.measurement.howTo}</p>
                  </div>
                </CardContent>
              </Card>
            </div>

            {/* Action Buttons */}
            <div className="flex flex-wrap gap-3">
              <Button onClick={handleSave} variant="outline">
                <Save className="mr-2 h-4 w-4" />
                Save Plan
              </Button>
              <Button onClick={handleExportPDF} variant="outline">
                <Download className="mr-2 h-4 w-4" />
                Export PDF
              </Button>
              <Button onClick={handleReset} variant="ghost">
                Create New Plan
              </Button>
            </div>

            <div className="text-xs text-muted-foreground text-center pt-4">
              All strategies are evidence-based and referenced to NICE, NHS, CDC, and peer-reviewed research.
            </div>
          </div>
        )}
      </CardContent>
    </Card>
  );
}
