import type { RelatedContentItem } from '@/components/seo/RelatedContent';

export type LinkIntelOverrideMap = Record<string, RelatedContentItem[]>;

export const LINK_INTEL_OVERRIDES: LinkIntelOverrideMap = {
  // AUTO_LINKS_START
  '/uk/guides/breathing-exercises-for-stress': [
    { href: '/guides/quick-calm-in-5-minutes', label: 'Quick calm in 5 minutes', description: 'A short, practical reset using breathing, grounding, and gentle movement.', typeBadge: 'Guide' },
    { href: '/guides/body-scan-for-stress', label: 'Body scan for stress relief', description: 'A simple body scan to release tension and reset your attention.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/tools/stress-tools', label: 'Stress Tools', description: 'Tool page for Stress Tools.', typeBadge: 'Tool' },
  ],
  '/us/guides/breathing-exercises-for-stress': [
    { href: '/guides/quick-calm-in-5-minutes', label: 'Quick calm in 5 minutes', description: 'A short, practical reset using breathing, grounding, and gentle movement.', typeBadge: 'Guide' },
    { href: '/guides/body-scan-for-stress', label: 'Body scan for stress relief', description: 'A simple body scan to release tension and reset your attention.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/tools/stress-tools', label: 'Stress Tools', description: 'Tool page for Stress Tools.', typeBadge: 'Tool' },
  ],
  '/uk/guides/focus-start': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/distraction-reset', label: 'Distraction reset plan', description: 'A quick routine to reset after a focus slip.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/working-with-school-adhd', label: 'Working with school (ADHD)', description: 'How to collaborate with schools using clear, practical steps.', typeBadge: 'Guide' },
    { href: '/guides/sleep/wind-down-routine', label: 'Wind-down routine', description: 'A short, repeatable routine before bed.', typeBadge: 'Guide' },
  ],
  '/us/guides/focus-start': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/distraction-reset', label: 'Distraction reset plan', description: 'A quick routine to reset after a focus slip.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/working-with-school-adhd', label: 'Working with school (ADHD)', description: 'How to collaborate with schools using clear, practical steps.', typeBadge: 'Guide' },
    { href: '/guides/sleep/wind-down-routine', label: 'Wind-down routine', description: 'A short, repeatable routine before bed.', typeBadge: 'Guide' },
  ],
  '/guides/breathing': [
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-focus', label: 'Breathing for focus', description: 'A short routine to reduce mental noise before starting a task.', typeBadge: 'Guide' },
    { href: '/guides/breathing/box-breathing', label: 'Box breathing step-by-step', description: 'A simple four-count pattern for calm and steady focus.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/box-breathing': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/coherent-breathing', label: 'Coherent breathing for steady calm', description: 'A slow, even rhythm designed for steadiness rather than urgency.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-focus', label: 'Breathing for focus', description: 'A short routine to reduce mental noise before starting a task.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/4-7-8-breathing': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/coherent-breathing': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/box-breathing', label: 'Box breathing step-by-step', description: 'A simple four-count pattern for calm and steady focus.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/sos-breathing-60': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/breathing-for-focus': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
  ],
  '/guides/breathing/breathing-for-sleep': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-focus', label: 'Breathing for focus', description: 'A short routine to reduce mental noise before starting a task.', typeBadge: 'Guide' },
    { href: '/guides/breathing-before-exams', label: 'Breathing before exams', description: 'A short breathing routine to steady focus before tests or assessments.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd': [
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/uk/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/planning-with-adhd', label: 'Planning with ADHD', description: 'Simple planning steps that reduce overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-parent-support', label: 'ADHD parent support', description: 'Practical next steps for parents and carers.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/adhd-focus-basics': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/uk/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/planning-with-adhd', label: 'Planning with ADHD', description: 'Simple planning steps that reduce overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/focus-sprints-for-adhd', label: 'Focus sprints for ADHD', description: 'Short focus blocks with recovery breaks for sustained attention.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/focus-sprints': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/uk/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/distraction-reset', label: 'Distraction reset plan', description: 'A quick routine to reset after a focus slip.', typeBadge: 'Guide' },
    { href: '/guides/focus-sprints-for-adhd', label: 'Focus sprints for ADHD', description: 'Short focus blocks with recovery breaks for sustained attention.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/distraction-reset': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/uk/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/focus-start', label: 'Focus starter routine', description: 'A short focus routine to help you begin a task with clarity and a steady pace. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/planning-with-adhd': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/working-with-school-adhd', label: 'Working with school (ADHD)', description: 'How to collaborate with schools using clear, practical steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-parent-support', label: 'ADHD parent support', description: 'Practical next steps for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/adhd-break-planning', label: 'ADHD break planning', description: 'Plan movement and reset breaks to sustain focus.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/working-with-school-adhd': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-parent-support', label: 'ADHD parent support', description: 'Practical next steps for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/planning-with-adhd', label: 'Planning with ADHD', description: 'Simple planning steps that reduce overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
  ],
  '/guides/focus-adhd/adhd-parent-support': [
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/working-with-school-adhd', label: 'Working with school (ADHD)', description: 'How to collaborate with schools using clear, practical steps.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/planning-with-adhd', label: 'Planning with ADHD', description: 'Simple planning steps that reduce overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress': [
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/worry-time-technique', label: 'Worry time technique', description: 'A structured way to reduce constant worry loops.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/grounding-5-4-3-2-1': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/worry-time-technique', label: 'Worry time technique', description: 'A structured way to reduce constant worry loops.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/quick-calm-in-5-minutes', label: 'Quick calm in 5 minutes', description: 'A short, practical reset using breathing, grounding, and gentle movement.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/panic-what-to-do-first': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/guides/sleep/night-waking-reset', label: 'Night waking reset', description: 'Steps to use if you wake during the night.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/breathing-for-anxiety': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/worry-time-technique', label: 'Worry time technique', description: 'A structured way to reduce constant worry loops.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/stress-reset-routine': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/guides/sleep/wind-down-routine', label: 'Wind-down routine', description: 'A short, repeatable routine before bed.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/worry-time-technique': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/when-to-seek-support-uk', label: 'When to seek support (UK)', description: 'Cautious guidance on when to seek professional help.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
  ],
  '/guides/anxiety-stress/when-to-seek-support-uk': [
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/panic-what-to-do-first', label: 'Panic: what to do first', description: 'Immediate steps to steady the body during a panic spike.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
  ],
  '/guides/sleep': [
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/wind-down-routine', label: 'Wind-down routine for better sleep', description: 'A gentle evening routine to help you settle and switch off.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/sleep-basics': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/wind-down-routine': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/wind-down-routine', label: 'Wind-down routine for better sleep', description: 'A gentle evening routine to help you settle and switch off.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/breathing-for-sleep': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/screen-time-and-sleep': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/night-waking-reset': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/distraction-reset', label: 'Distraction reset plan', description: 'A quick routine to reset after a focus slip.', typeBadge: 'Guide' },
  ],
  '/guides/sleep/sleep-and-anxiety': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/sleep-reset-for-shift-workers', label: 'Sleep reset for shift workers', description: 'Small steps to manage sleep when your schedule changes.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading': [
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/what-is-dyslexia', label: 'What is dyslexia?', description: 'A clear overview of dyslexia and common strengths.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/phonics-at-home', label: 'Phonics at home', description: 'A short daily phonics routine for families.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/what-is-dyslexia': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/phonics-at-home', label: 'Phonics at home', description: 'A short daily phonics routine for families.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/reading-confidence': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/phonics-at-home', label: 'Phonics at home', description: 'A short daily phonics routine for families.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/reading-confidence-in-class', label: 'Reading confidence in class', description: 'Classroom strategies to support reading confidence and participation.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/phonics-at-home': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/reading-routine-at-home', label: 'Reading routine at home', description: 'Short daily reading routines for dyslexia support.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/support-at-school': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/what-is-dyslexia', label: 'What is dyslexia?', description: 'A clear overview of dyslexia and common strengths.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/phonics-at-home', label: 'Phonics at home', description: 'A short daily phonics routine for families.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/assistive-tech-uk': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/what-is-dyslexia', label: 'What is dyslexia?', description: 'A clear overview of dyslexia and common strengths.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/parent-carer-next-steps', label: 'Parent and carer next steps', description: 'Simple next steps for families supporting dyslexia.', typeBadge: 'Guide' },
    { href: '/guides/reading-routine-at-home', label: 'Reading routine at home', description: 'Short daily reading routines for dyslexia support.', typeBadge: 'Guide' },
  ],
  '/guides/dyslexia-reading/parent-carer-next-steps': [
    { href: '/guides/dyslexia-reading', label: 'Dyslexia & Reading Support', description: 'Practical reading support for dyslexia, including home routines and school strategies. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/what-is-dyslexia', label: 'What is dyslexia?', description: 'A clear overview of dyslexia and common strengths.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-parent-support', label: 'ADHD parent support', description: 'Practical next steps for parents and carers.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support': [
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/sensory-overload-plan', label: 'Sensory overload plan', description: 'Steps to help during sensory overload.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/autism-basics': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/autism-transition-support', label: 'Autism transition support', description: 'Predictable steps to make transitions smoother.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/sensory-overload-plan': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/meltdown-vs-shutdown': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/routines-and-transitions': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/sensory-overload-plan', label: 'Sensory overload plan', description: 'Steps to help during sensory overload.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/school-support-uk-send': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/parent-carer-support', label: 'Parent and carer support', description: 'Support strategies for parents and carers.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/support-at-school', label: 'Support at school', description: 'Practical classroom strategies for dyslexia support.', typeBadge: 'Guide' },
  ],
  '/guides/autism-support/parent-carer-support': [
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/school-support-uk-send', label: 'School support (UK SEND)', description: 'Practical guidance for school support pathways in the UK.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/meltdown-vs-shutdown', label: 'Meltdown vs shutdown', description: 'Understanding different stress responses.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-parent-support', label: 'ADHD parent support', description: 'Practical next steps for parents and carers.', typeBadge: 'Guide' },
  ],
  '/guides/quick-calm-in-5-minutes': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/body-scan-for-stress', label: 'Body scan for stress relief', description: 'A simple body scan to release tension and reset your attention.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/grounding-5-4-3-2-1', label: 'Grounding 5-4-3-2-1', description: 'A sensory grounding technique for quick calm.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/tools/stress-tools', label: 'Stress Tools', description: 'Tool page for Stress Tools.', typeBadge: 'Tool' },
  ],
  '/guides/body-scan-for-stress': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/quick-calm-in-5-minutes', label: 'Quick calm in 5 minutes', description: 'A short, practical reset using breathing, grounding, and gentle movement.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress/stress-reset-routine', label: 'Stress reset routine', description: 'A short routine for calming the body and mind.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/tools/stress-tools', label: 'Stress Tools', description: 'Tool page for Stress Tools.', typeBadge: 'Tool' },
  ],
  '/guides/wind-down-routine': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/wind-down-routine', label: 'Wind-down routine', description: 'A short, repeatable routine before bed.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/sleep-reset-for-shift-workers': [
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep/breathing-for-sleep', label: 'Breathing for sleep', description: 'Gentle breathing to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/sleep/screen-time-and-sleep', label: 'Screen time and sleep', description: 'How to reduce screen impact on sleep without drastic changes.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
  ],
  '/guides/focus-sprints-for-adhd': [
    { href: '/guides/adhd-break-planning', label: 'ADHD break planning', description: 'Plan movement and reset breaks to sustain focus.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/tools/adhd-focus-lab', label: 'Adhd Focus Lab', description: 'Tool page for Adhd Focus Lab.', typeBadge: 'Tool' },
  ],
  '/guides/adhd-break-planning': [
    { href: '/guides/focus-sprints-for-adhd', label: 'Focus sprints for ADHD', description: 'Short focus blocks with recovery breaks for sustained attention.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/planning-with-adhd', label: 'Planning with ADHD', description: 'Simple planning steps that reduce overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/guides/autism-sensory-reset': [
    { href: '/guides/autism-transition-support', label: 'Autism transition support', description: 'Predictable steps to make transitions smoother.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/sensory-overload-plan', label: 'Sensory overload plan', description: 'Steps to help during sensory overload.', typeBadge: 'Guide' },
    { href: '/guides/breathing-for-sensory-overload', label: 'Breathing for sensory overload', description: 'Gentle breathing steps to support regulation during sensory overwhelm.', typeBadge: 'Guide' },
    { href: '/tools/autism-tools', label: 'Autism Tools', description: 'Tool page for Autism Tools.', typeBadge: 'Tool' },
  ],
  '/guides/autism-transition-support': [
    { href: '/guides/autism-sensory-reset', label: 'Autism sensory reset', description: 'A gentle plan for sensory overload moments.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/routines-and-transitions', label: 'Routines and transitions', description: 'Predictable steps that reduce anxiety around change.', typeBadge: 'Guide' },
    { href: '/tools/autism-tools', label: 'Autism Tools', description: 'Tool page for Autism Tools.', typeBadge: 'Tool' },
  ],
  '/guides/reading-routine-at-home': [
    { href: '/guides/reading-confidence-in-class', label: 'Reading confidence in class', description: 'Classroom strategies to support reading confidence and participation.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/phonics-at-home', label: 'Phonics at home', description: 'A short daily phonics routine for families.', typeBadge: 'Guide' },
    { href: '/tools/adhd-focus-lab', label: 'Adhd Focus Lab', description: 'Tool page for Adhd Focus Lab.', typeBadge: 'Tool' },
  ],
  '/guides/reading-confidence-in-class': [
    { href: '/guides/reading-routine-at-home', label: 'Reading routine at home', description: 'Short daily reading routines for dyslexia support.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/reading-confidence', label: 'Reading confidence', description: 'Short steps to build confidence and reduce reading anxiety.', typeBadge: 'Guide' },
    { href: '/guides/dyslexia-reading/assistive-tech-uk', label: 'Assistive tech (UK)', description: 'Accessible tools and software that support reading.', typeBadge: 'Guide' },
    { href: '/tools/anxiety-tools', label: 'Anxiety Tools', description: 'Tool page for Anxiety Tools.', typeBadge: 'Tool' },
  ],
  '/guides/breathing-before-exams': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-focus', label: 'Breathing for focus', description: 'A short routine to reduce mental noise before starting a task.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing/box-breathing', label: 'Box breathing step-by-step', description: 'A simple four-count pattern for calm and steady focus.', typeBadge: 'Guide' },
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
  ],
  '/guides/breathing-for-sensory-overload': [
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/guides/breathing/4-7-8-breathing', label: '4-7-8 breathing explained', description: 'A paced breathing method often used for relaxation at night.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-sleep', label: 'Breathing for sleep', description: 'A calm breathing routine to support sleep onset.', typeBadge: 'Guide' },
    { href: '/guides/breathing/breathing-for-focus', label: 'Breathing for focus', description: 'A short routine to reduce mental noise before starting a task.', typeBadge: 'Guide' },
    { href: '/guides/breathing/sos-breathing-60', label: '60-second SOS breathing', description: 'A quick reset for acute stress or overwhelm.', typeBadge: 'Guide' },
    { href: '/guides/autism-support/sensory-overload-plan', label: 'Sensory overload plan', description: 'Steps to help during sensory overload.', typeBadge: 'Guide' },
  ],
  '/tools/adhd-focus-lab': [
    { href: '/guides/focus-sprints-for-adhd', label: 'Focus sprints for ADHD', description: 'Short focus blocks with recovery breaks for sustained attention.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/adhd-tools': [
    { href: '/guides/adhd-break-planning', label: 'ADHD break planning', description: 'Plan movement and reset breaks to sustain focus.', typeBadge: 'Guide' },
    { href: '/guides/focus-sprints-for-adhd', label: 'Focus sprints for ADHD', description: 'Short focus blocks with recovery breaks for sustained attention.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-focus-lab', label: 'Adhd Focus Lab', description: 'Tool page for Adhd Focus Lab.', typeBadge: 'Tool' },
  ],
  '/tools/anxiety-tools': [
    { href: '/guides/anxiety-stress/breathing-for-anxiety', label: 'Breathing for anxiety', description: 'Simple breathing steps to reduce tension and worry.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/autism-tools': [
    { href: '/guides/autism-support/autism-basics', label: 'Autism basics', description: 'A clear overview of autism and common support needs.', typeBadge: 'Guide' },
    { href: '/guides/autism-transition-support', label: 'Autism transition support', description: 'Predictable steps to make transitions smoother.', typeBadge: 'Guide' },
    { href: '/guides/autism-support', label: 'Autism Support', description: 'Educational guidance for autism support, routines, and sensory needs with practical tools and resources.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/breath-ladder': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/breath-tools', label: 'Breath Tools', description: 'Tool page for Breath Tools.', typeBadge: 'Tool' },
  ],
  '/tools/breath-tools': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/breath-ladder', label: 'Breath Ladder', description: 'Tool page for Breath Ladder.', typeBadge: 'Tool' },
  ],
  '/tools/colour-path': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/depression-tools': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/focus-tiles': [
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/tools/focus-training', label: 'Focus Training', description: 'Tool page for Focus Training.', typeBadge: 'Tool' },
  ],
  '/tools/focus-training': [
    { href: '/guides/focus-adhd/focus-sprints', label: 'Focus sprints that feel doable', description: 'Short focus blocks with recovery breaks.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd/adhd-focus-basics', label: 'ADHD focus basics', description: 'A simple overview of what helps focus when attention is scattered.', typeBadge: 'Guide' },
    { href: '/guides/focus-adhd', label: 'Focus & ADHD Support', description: 'Guidance for focus, ADHD routines and classroom support, with practical tools and short steps.', typeBadge: 'Guide' },
    { href: '/tools/focus-tiles', label: 'Focus Tiles', description: 'Tool page for Focus Tiles.', typeBadge: 'Tool' },
  ],
  '/tools/mood-tools': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/roulette': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/breathing', label: 'Breathing Exercises', description: 'Practical breathing guidance for calm, focus, stress and sleep. Educational information only with clear next steps.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/sleep-tools': [
    { href: '/guides/sleep/sleep-and-anxiety', label: 'Sleep and anxiety', description: 'How to calm worry that affects sleep.', typeBadge: 'Guide' },
    { href: '/guides/sleep/sleep-basics', label: 'Sleep basics', description: 'A simple overview of sleep foundations and common myths.', typeBadge: 'Guide' },
    { href: '/guides/sleep', label: 'Sleep Support', description: 'Guidance for better sleep with wind-down routines, breathing and practical steps. Educational information only.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/tools/stress-tools': [
    { href: '/uk/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/us/guides/breathing-exercises-for-stress', label: 'Breathing exercises for stress', description: 'A calm, practical breathing routine to support stress regulation. Educational guidance only.', typeBadge: 'Guide' },
    { href: '/guides/anxiety-stress', label: 'Anxiety & Stress Support', description: 'Calm routines, grounding steps and practical guidance for stress and anxiety. Educational information only.', typeBadge: 'Guide' },
    { href: '/tools/adhd-tools', label: 'Adhd Tools', description: 'Tool page for Adhd Tools.', typeBadge: 'Tool' },
  ],
  '/trust': [
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
  ],
  '/trust/accessibility': [
    { href: '/uk/trust/accessibility', label: 'Accessibility', description: 'Accessibility trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/accessibility', label: 'Accessibility', description: 'Accessibility trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/contact': [
    { href: '/uk/trust/contact', label: 'Contact', description: 'Contact trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/contact', label: 'Contact', description: 'Contact trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/disclaimer': [
    { href: '/uk/trust/disclaimer', label: 'Disclaimer', description: 'Disclaimer trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/disclaimer', label: 'Disclaimer', description: 'Disclaimer trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/evidence-policy': [
    { href: '/uk/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/privacy': [
    { href: '/uk/trust/privacy', label: 'Privacy', description: 'Privacy trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/privacy', label: 'Privacy', description: 'Privacy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/safeguarding': [
    { href: '/uk/trust/safeguarding', label: 'Safeguarding', description: 'Safeguarding trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/safeguarding', label: 'Safeguarding', description: 'Safeguarding trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/trust/terms': [
    { href: '/uk/trust/terms', label: 'Terms', description: 'Terms trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/terms', label: 'Terms', description: 'Terms trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust': [
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/uk/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
  ],
  '/us/trust': [
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/us/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/accessibility': [
    { href: '/trust/accessibility', label: 'Accessibility', description: 'Accessibility trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/accessibility': [
    { href: '/trust/accessibility', label: 'Accessibility', description: 'Accessibility trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/contact': [
    { href: '/trust/contact', label: 'Contact', description: 'Contact trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/contact': [
    { href: '/trust/contact', label: 'Contact', description: 'Contact trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/disclaimer': [
    { href: '/trust/disclaimer', label: 'Disclaimer', description: 'Disclaimer trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/disclaimer': [
    { href: '/trust/disclaimer', label: 'Disclaimer', description: 'Disclaimer trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/evidence-policy': [
    { href: '/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/evidence-policy': [
    { href: '/trust/evidence-policy', label: 'Evidence Policy', description: 'Evidence Policy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/privacy': [
    { href: '/trust/privacy', label: 'Privacy', description: 'Privacy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/privacy': [
    { href: '/trust/privacy', label: 'Privacy', description: 'Privacy trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/safeguarding': [
    { href: '/trust/safeguarding', label: 'Safeguarding', description: 'Safeguarding trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/safeguarding': [
    { href: '/trust/safeguarding', label: 'Safeguarding', description: 'Safeguarding trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/uk/trust/terms': [
    { href: '/trust/terms', label: 'Terms', description: 'Terms trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/uk/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  '/us/trust/terms': [
    { href: '/trust/terms', label: 'Terms', description: 'Terms trust information.', typeBadge: 'Trust' },
    { href: '/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
    { href: '/us/trust', label: 'Trust', description: 'Trust and safety information.', typeBadge: 'Trust' },
  ],
  // AUTO_LINKS_END
};
